"""Tests for the TopoDB refusal rules, round-trip, CLI and comparison helpers.

Every test builds its own throw-away database in a tmp_path; nothing here
touches the real DB at $TOPODB_PATH.
"""
from __future__ import annotations

import json

import pytest

from topodb import cli, compare, report
from topodb.api import TopoDB


@pytest.fixture()
def db(tmp_path):
    return TopoDB(str(tmp_path / "t.sqlite"))


def _dataset(db, id="synthetic/circle", domain="synthetic"):
    return db.add_dataset(id=id, domain=domain, title="unit circle, 200 points",
                          source="generated by test", provenance="synthetic_control",
                          n_objects=200, ambient_dim=2)


def _run(db, dataset_id="synthetic/circle", tier="X", method="alpha"):
    return db.add_run(dataset_id=dataset_id, method=method, coeff_field=2, max_dim=2,
                      params={"max_alpha_sq": "inf"}, script="test_topodb.py",
                      command="pytest", tier=tier, seed="0")


# --------------------------------------------------------------- refusals
class TestRefusalRules:
    def test_p_value_without_null_model_is_refused(self, db):
        _dataset(db)
        r = _run(db)
        with pytest.raises(ValueError, match="p_value requires null_model and n_null"):
            db.add_statistic(r, "iqr_over_median", 0.45, p_value=0.01, n_null=100)
        with pytest.raises(ValueError, match="p_value requires null_model and n_null"):
            db.add_statistic(r, "iqr_over_median", 0.45, p_value=0.01, null_model="uniform box")
        assert db.con.execute("SELECT count(*) FROM statistic").fetchone()[0] == 0

    def test_statistic_without_p_value_is_accepted(self, db):
        """A source with no null must be storable: the statistic alone, no invented p."""
        _dataset(db)
        r = _run(db)
        db.add_statistic(r, "psi6", 0.83)
        row = db.con.execute("SELECT * FROM statistic").fetchone()
        assert row["p_value"] is None and row["null_model"] is None and row["value"] == 0.83

    def test_p_value_with_its_null_is_accepted(self, db):
        _dataset(db)
        r = _run(db)
        db.add_statistic(r, "h1_bar1", 1.0, null_model="50 matched uniform-box nulls",
                         n_null=50, p_value=1 / 51, p_method="rank")
        row = db.con.execute("SELECT * FROM statistic").fetchone()
        assert row["n_null"] == 50 and row["p_value"] == pytest.approx(1 / 51)

    def test_matches_requires_expected(self, db):
        """`matches` is NULL unless the source pre-stated an expectation."""
        _dataset(db)
        r1, r2 = _run(db), _run(db)
        db.add_betti(r1, {0: 1, 1: 1, 2: 0})                       # no pre-registration
        db.add_betti(r2, {0: 1, 1: 1, 2: 0}, expected={0: 1, 1: 1, 2: 0})
        no_exp = db.con.execute("SELECT * FROM betti WHERE run_id=?", (r1,)).fetchall()
        assert all(row["expected"] is None and row["matches"] is None for row in no_exp)
        with_exp = db.con.execute("SELECT * FROM betti WHERE run_id=?", (r2,)).fetchall()
        assert all(row["matches"] == 1 for row in with_exp)

    def test_matches_is_zero_on_disagreement(self, db):
        _dataset(db)
        r = _run(db)
        db.add_betti(r, {2: 21}, expected={2: 22})
        row = db.con.execute("SELECT * FROM betti WHERE run_id=?", (r,)).fetchone()
        assert row["matches"] == 0 and row["value"] == 21 and row["expected"] == 22

    def test_partial_expectation_leaves_the_rest_ungated(self, db):
        _dataset(db)
        r = _run(db)
        db.add_betti(r, {0: 1, 1: 2, 2: 1}, expected={1: 2})
        rows = {row["dim"]: row for row in db.con.execute(
            "SELECT * FROM betti WHERE run_id=?", (r,)).fetchall()}
        assert rows[1]["matches"] == 1
        assert rows[0]["matches"] is None and rows[2]["matches"] is None

    @pytest.mark.parametrize("tier", ["Z", "a", "proved", ""])
    def test_bad_tier_is_refused(self, db, tier):
        _dataset(db)
        with pytest.raises(ValueError, match="tier must be one of"):
            _run(db, tier=tier)
        with pytest.raises(ValueError, match="tier must be one of"):
            db.add_finding(claim="x", verdict="null", tier=tier)

    def test_bad_method_is_refused(self, db):
        _dataset(db)
        with pytest.raises(ValueError, match="method must be one of"):
            _run(db, method="lower_star")   # the schema's name is lower_star_graph

    def test_bad_verdict_is_refused_by_the_schema(self, db):
        import sqlite3
        _dataset(db)
        r = _run(db)
        with pytest.raises(sqlite3.IntegrityError):
            db.add_finding(claim="x", verdict="proved", tier="X", run_id=r)

    def test_unknown_domain_is_refused_by_the_schema(self, db):
        import sqlite3
        with pytest.raises(sqlite3.IntegrityError):
            db.add_dataset(id="x/y", domain="cosmology", title="t", source="s",
                           provenance="observation")


# -------------------------------------------------------------- round trip
class TestRoundTrip:
    def test_full_run_round_trips(self, db):
        _dataset(db)
        run = db.add_run(dataset_id="synthetic/circle", method="alpha", coeff_field=2, max_dim=2,
                         params={"max_alpha_sq": "inf", "n": 200}, preprocessing="none",
                         script="simple_suite.py", command="python simple_suite.py --case P1",
                         tier="X", seed="0", wall_sec=0.79, peak_mb=173.8)
        db.add_betti(run, {0: 1, 1: 1, 2: 0}, expected={0: 1, 1: 1, 2: 0})
        db.add_bars(run, 1, [(0.03, 0.86), (0.032, 0.049), (0.027, 0.043)])
        db.add_bars(run, 0, [(0.0, None), (0.0, 0.048)])
        db.add_statistic(run, "p1_over_p2", 47.86)
        db.add_statistic(run, "h1_bar1", 1.0, null_model="50 uniform-box nulls", n_null=50,
                         p_value=0.0196, p_method="rank")
        db.add_control(run, "known_answer", "circle recovers b1=1", passed=True, detail="ratio 47.9")
        fid = db.add_finding(run_id=run, claim="alpha recovers the circle", verdict="recovered",
                             tier="X", caveat="one seed", reference="report.json")

        r = db.con.execute("SELECT * FROM run WHERE id=?", (run,)).fetchone()
        assert r["method"] == "alpha" and r["tier"] == "X" and r["seed"] == "0"
        assert json.loads(r["params_json"]) == {"max_alpha_sq": "inf", "n": 200}
        assert r["created"] and r["command"].endswith("--case P1")

        betti = {row["dim"]: (row["value"], row["expected"], row["matches"])
                 for row in db.con.execute("SELECT * FROM betti WHERE run_id=?", (run,))}
        assert betti == {0: (1, 1, 1), 1: (1, 1, 1), 2: (0, 0, 1)}

        bars1 = db.con.execute(
            "SELECT birth, death, rank FROM bar WHERE run_id=? AND dim=1 ORDER BY rank",
            (run,)).fetchall()
        assert [b["rank"] for b in bars1] == [1, 2, 3]
        assert bars1[0]["birth"] == pytest.approx(0.03) and bars1[0]["death"] == pytest.approx(0.86)

        bars0 = db.con.execute(
            "SELECT birth, death, rank FROM bar WHERE run_id=? AND dim=0 ORDER BY rank",
            (run,)).fetchall()
        assert bars0[0]["death"] is None, "the infinite bar must rank first and store death NULL"

        assert db.con.execute("SELECT count(*) FROM statistic WHERE run_id=?",
                              (run,)).fetchone()[0] == 2
        c = db.con.execute("SELECT * FROM control WHERE run_id=?", (run,)).fetchone()
        assert c["passed"] == 1 and c["kind"] == "known_answer"
        f = db.con.execute("SELECT * FROM finding WHERE id=?", (fid,)).fetchone()
        assert f["verdict"] == "recovered" and f["run_id"] == run

    def test_bars_are_ranked_by_persistence_and_truncated(self, db):
        _dataset(db)
        run = _run(db)
        bars = [(0.0, 0.1 * i) for i in range(1, 80)]
        db.add_bars(run, 1, bars)
        rows = db.con.execute(
            "SELECT birth, death, rank FROM bar WHERE run_id=? ORDER BY rank", (run,)).fetchall()
        assert len(rows) == 50, "add_bars keeps the top 50 by default -- the truncation compare.py warns about"
        assert rows[0]["death"] == pytest.approx(7.9)
        deaths = [r["death"] for r in rows]
        assert deaths == sorted(deaths, reverse=True)

    def test_search_finds_datasets_and_findings(self, db):
        _dataset(db, id="astro/wmap_ilc9", domain="astro")
        db.add_finding(dataset_id="astro/wmap_ilc9", claim="no vortex excess over the null",
                       verdict="null", tier="X")
        assert any(r["kind"] == "finding" for r in db.search("vortex"))

    def test_summary_counts(self, db):
        _dataset(db)
        r = _run(db, tier="B")
        db.add_bars(r, 1, [(0.0, 1.0)])
        db.add_control(r, "known_answer", "k", passed=True)
        db.add_finding(run_id=r, claim="c", verdict="null", tier="B")
        s = db.summary()
        assert s["datasets_by_domain"] == {"synthetic": 1}
        assert s["runs_by_tier"] == {"B": 1} and s["runs_by_method"] == {"alpha": 1}
        assert s["controls_passed"] == {"passed": 1}
        assert s["findings_by_verdict"] == {"null": 1} and s["bars"] == 1


# ----------------------------------------------------------------- compare
class TestCompare:
    """The hand-computed cases.

    Two trivial diagrams, one point each: A={(0,1)}, B={(0,1.5)}.
      * matching the points costs max(|0-0|, |1-1.5|) = 0.5
      * sending both to the diagonal costs max(1/2, 1.5/2) = 0.75
    so the bottleneck distance is min(0.5, 0.75) = 0.5, by hand.
    (The pair (0,1) vs (0,2) is deliberately NOT used: both strategies cost 1.0
    there, so it would not discriminate between them.)

    And A={} vs B={(0,1)}: the only option is the diagonal, 1/2 = 0.5.
    1-Wasserstein on A={(0,1)} vs B={(0,1.5)} is the single matched cost, 0.5.
    """

    def _two_runs(self, db, bars_a, bars_b, dim=1):
        _dataset(db)
        ra, rb = _run(db), _run(db)
        if bars_a:
            db.add_bars(ra, dim, bars_a)
        if bars_b:
            db.add_bars(rb, dim, bars_b)
        return ra, rb

    def test_bottleneck_matches_hand_computation(self, db):
        ra, rb = self._two_runs(db, [(0.0, 1.0)], [(0.0, 1.5)])
        d, info = compare.bottleneck(ra, rb, 1, db=db)
        assert d == pytest.approx(0.5, abs=1e-9)
        assert info["metric"] == "bottleneck" and info["methods_comparable"] is True
        assert "truncated to the top 50" in info["caveat"]

    def test_bottleneck_against_an_empty_diagram_is_half_the_persistence(self, db):
        ra, rb = self._two_runs(db, [], [(0.0, 1.0)])
        d, _ = compare.bottleneck(ra, rb, 1, db=db)
        assert d == pytest.approx(0.5, abs=1e-9)

    def test_bottleneck_of_a_run_with_itself_is_zero(self, db):
        ra, _ = self._two_runs(db, [(0.0, 1.0), (0.2, 0.9)], [(0.0, 1.0)])
        d, _ = compare.bottleneck(ra, ra, 1, db=db)
        assert d == pytest.approx(0.0)

    def test_wasserstein_matches_hand_computation(self, db):
        ra, rb = self._two_runs(db, [(0.0, 1.0)], [(0.0, 1.5)])
        d, info = compare.wasserstein(ra, rb, 1, db=db, order=1.0)
        assert d == pytest.approx(0.5, abs=1e-6)
        assert "wasserstein" in info["metric"]

    def test_infinite_bars_are_dropped_by_default_and_counted(self, db):
        ra, rb = self._two_runs(db, [(0.0, None), (0.0, 1.0)], [(0.0, 1.5)], dim=0)
        d, info = compare.bottleneck(ra, rb, 0, db=db)
        assert d == pytest.approx(0.5, abs=1e-9)
        assert info["run_a"]["n_infinite_dropped"] == 1
        assert info["run_a"]["n_points_used"] == 1 and info["run_a"]["n_bars_stored"] == 2

    def test_keeping_infinite_bars_gives_an_infinite_distance(self, db):
        ra, rb = self._two_runs(db, [(0.0, None)], [(0.0, 1.5)], dim=0)
        d, _ = compare.bottleneck(ra, rb, 0, db=db, infinite="keep")
        assert d == float("inf"), "this is why 'drop' is the default"

    def test_capping_infinite_bars(self, db):
        ra, rb = self._two_runs(db, [(0.0, None)], [(0.0, 1.5)], dim=0)
        d, _ = compare.bottleneck(ra, rb, 0, db=db, infinite="cap", cap_value=2.0)
        assert d == pytest.approx(0.5, abs=1e-9)

    def test_nearest_excludes_runs_without_bars_and_says_how_many(self, db):
        _dataset(db)
        ref = _run(db)
        db.add_bars(ref, 1, [(0.0, 1.0)])
        close = _run(db)
        db.add_bars(close, 1, [(0.0, 1.1)])
        far = _run(db)
        db.add_bars(far, 1, [(0.0, 9.0)])
        chain = db.add_run(dataset_id="synthetic/circle", method="chain_complex", coeff_field=0,
                           params={}, script="s", command="c", tier="B")
        db.add_betti(chain, {2: 22})                       # Betti but no filtration, hence no bars

        res = compare.nearest(ref, k=2, dim=1, db=db)
        assert [n["run_id"] for n in res["neighbours"]] == [close, far]
        assert res["neighbours"][0]["distance"] == pytest.approx(0.1, abs=1e-9)
        assert res["excluded_no_bars"] == 1
        assert res["n_compared"] == 2
        assert "truncated to the top 50" in res["caveat"]

    def test_nearest_refuses_to_mix_methods_by_default(self, db):
        _dataset(db)
        ref = _run(db, method="alpha")
        db.add_bars(ref, 1, [(0.0, 1.0)])
        other = _run(db, method="rips")
        db.add_bars(other, 1, [(0.0, 1.0)])
        assert compare.nearest(ref, dim=1, db=db)["excluded_other_method"] == 1
        assert compare.nearest(ref, dim=1, db=db)["neighbours"] == []
        mixed = compare.nearest(ref, dim=1, db=db, same_method=False)
        assert [n["run_id"] for n in mixed["neighbours"]] == [other]

    def test_missing_run_raises(self, db):
        with pytest.raises(KeyError):
            compare.load_diagram(db, 999, 1)


# -------------------------------------------------------------------- report
class TestReport:
    def test_report_separates_prestated_from_ungated(self, db, tmp_path):
        _dataset(db)
        db.add_dataset(id="astro/wmap", domain="astro", title="WMAP ILC9", source="LAMBDA",
                       provenance="observation")
        gated = _run(db)
        db.add_betti(gated, {1: 1}, expected={1: 1})
        db.add_control(gated, "known_answer", "circle b1=1", passed=True)
        ungated = db.add_run(dataset_id="astro/wmap", method="cubical", coeff_field=2, params={},
                             script="s", command="c", tier="X")
        db.add_betti(ungated, {1: 4})
        db.add_finding(run_id=ungated, claim="no excess", verdict="null", tier="X")
        db.add_statistic(ungated, "iqr_over_median", 0.45)

        data = report.build(db)
        assert data["runs_by_tier"] == {"X": 2}
        assert data["betti_vs_prestated_expectation"]["matched"] == 1
        assert data["betti_vs_prestated_expectation"]["no_expectation_recorded"] == 1
        ka = data["known_answer_controls"]
        assert [d["dataset"] for d in ka["all_passed"]] == ["synthetic/circle"]
        assert "astro/wmap" in [d["dataset"] for d in ka["datasets_with_no_known_answer_control"]]
        assert [f["verdict"] for f in data["findings_null_or_inconclusive"]] == ["null"]
        assert data["totals"]["statistics_without_p_value"] == 1
        assert data["runs_without_any_bars"]["count"] == 2

        out = tmp_path / "r.json"
        report.write(str(out), db)
        assert json.loads(out.read_text())["totals"]["runs"] == 2

    def test_report_lists_failed_known_answer_controls(self, db):
        _dataset(db)
        r = _run(db)
        db.add_control(r, "known_answer", "RP2 over Z/3", passed=False, detail="over budget")
        data = report.build(db)
        assert data["known_answer_controls"]["all_passed"] == []
        assert data["known_answer_controls"]["some_failed"][0]["n_failed"] == 1


# ----------------------------------------------------------------------- CLI
def _seed_cli_db(path):
    db = TopoDB(path)
    db.add_dataset(id="synthetic/circle", domain="synthetic", title="unit circle",
                   source="generated by test", provenance="synthetic_control", n_objects=200)
    db.add_dataset(id="mathematics/k3", domain="mathematics", title="resolved K3",
                   source="Mayer-Vietoris", provenance="synthetic_control")
    r = db.add_run(dataset_id="synthetic/circle", method="alpha", coeff_field=2, max_dim=2,
                   params={"max_alpha_sq": "inf"}, script="s.py", command="python s.py", tier="X")
    db.add_betti(r, {0: 1, 1: 1, 2: 0}, expected={0: 1, 1: 1, 2: 0})
    db.add_bars(r, 1, [(0.03, 0.86), (0.03, 0.05)])
    db.add_bars(r, 0, [(0.0, None)])
    db.add_statistic(r, "p1_over_p2", 47.86)
    db.add_control(r, "known_answer", "circle recovers b1=1", passed=True, detail="ratio 47.9")
    db.add_finding(run_id=r, claim="the circle is recovered", verdict="recovered", tier="X")
    r2 = db.add_run(dataset_id="synthetic/circle", method="alpha", coeff_field=2,
                    params={}, script="s.py", command="python s.py", tier="X")
    db.add_bars(r2, 1, [(0.03, 0.9)])
    chain = db.add_run(dataset_id="mathematics/k3", method="chain_complex", coeff_field=0,
                       params={"N": 8}, script="mv.py", command="python mv.py", tier="B")
    db.add_betti(chain, {0: 1, 1: 0, 2: 22, 3: 0, 4: 1})
    db.add_finding(run_id=chain, claim="b2=22 for the resolved K3", verdict="recovered", tier="B")
    return db, r, r2, chain


class TestCLI:
    @pytest.fixture()
    def seeded(self, tmp_path):
        path = str(tmp_path / "cli.sqlite")
        db, r, r2, chain = _seed_cli_db(path)
        return path, r, r2, chain

    def _run_cli(self, path, *argv):
        return cli.main(["--db", path, *argv])

    def test_summary(self, seeded, capsys):
        path, *_ = seeded
        assert self._run_cli(path, "summary") == 0
        out = capsys.readouterr().out
        assert "runs_by_tier" in out and "synthetic" in out and "mathematics" in out

    def test_search_hit_and_miss(self, seeded, capsys):
        path, *_ = seeded
        assert self._run_cli(path, "search", "circle") == 0
        assert "circle" in capsys.readouterr().out
        assert self._run_cli(path, "search", "zzzznotpresent") == 1

    def test_datasets_and_domain_filter(self, seeded, capsys):
        path, *_ = seeded
        self._run_cli(path, "datasets")
        out = capsys.readouterr().out
        assert "synthetic/circle" in out and "mathematics/k3" in out
        self._run_cli(path, "datasets", "--domain", "mathematics")
        out = capsys.readouterr().out
        assert "mathematics/k3" in out and "synthetic/circle" not in out

    def test_runs_and_dataset_filter(self, seeded, capsys):
        path, r, r2, chain = seeded
        self._run_cli(path, "runs")
        assert str(chain) in capsys.readouterr().out
        self._run_cli(path, "runs", "--dataset", "circle")
        out = capsys.readouterr().out
        assert "synthetic/circle" in out and "mathematics/k3" not in out
        self._run_cli(path, "runs", "--tier", "B")
        assert "chain_complex" in capsys.readouterr().out

    def test_betti(self, seeded, capsys):
        path, *_ = seeded
        assert self._run_cli(path, "betti") == 0
        out = capsys.readouterr().out
        assert "0:1 1:1 2:0" in out and "match" in out and "2:22" in out
        self._run_cli(path, "betti", "--domain", "mathematics")
        assert "synthetic/circle" not in capsys.readouterr().out

    def test_show_full_record(self, seeded, capsys):
        path, r, *_ = seeded
        assert self._run_cli(path, "show", str(r)) == 0
        out = capsys.readouterr().out
        for expected in ("dataset:", "params:", "max_alpha_sq", "betti:", "controls:",
                         "known_answer", "statistics:", "p1_over_p2", "top bars", "findings:",
                         "the circle is recovered"):
            assert expected in out, expected

    def test_show_of_a_run_without_bars_says_so(self, seeded, capsys):
        path, _, _, chain = seeded
        self._run_cli(path, "show", str(chain))
        assert "no bars stored" in capsys.readouterr().out

    def test_show_missing_run(self, seeded, capsys):
        path, *_ = seeded
        assert self._run_cli(path, "show", "9999") == 1

    def test_export_json(self, seeded, tmp_path, capsys):
        path, *_ = seeded
        out = tmp_path / "export.json"
        assert self._run_cli(path, "export", "--json", str(out)) == 0
        data = json.loads(out.read_text())
        assert data["totals"]["runs"] == 3 and data["runs_by_tier"] == {"B": 1, "X": 2}
        assert data["known_answer_controls"]["all_passed"][0]["dataset"] == "synthetic/circle"

    def test_nearest_prints_the_approximation_warning(self, seeded, capsys):
        path, r, r2, chain = seeded
        assert self._run_cli(path, "nearest", str(r), "--dim", "1") == 0
        out = capsys.readouterr().out
        assert "APPROXIMATE" in out and "truncated to the top 50" in out
        assert "excluded for having no stored bars" in out
        assert str(r2) in out

    def test_distance_between_two_runs(self, seeded, capsys):
        path, r, r2, _ = seeded
        assert self._run_cli(path, "distance", str(r), str(r2), "--dim", "1") == 0
        out = capsys.readouterr().out
        assert "bottleneck" in out and "APPROXIMATE" in out

    def test_help_does_not_need_a_db(self, capsys):
        with pytest.raises(SystemExit) as e:
            cli.main(["--help"])
        assert e.value.code == 0


# ------------------------------------------------- the shared-database guard
class TestOwnershipScopedReset:
    """The database lives outside git and other sessions write into it.

    A global wipe before re-ingesting would destroy their rows, so the reset is
    scoped to rows this backfill created. These tests pin that.
    """

    def test_wipe_owned_deletes_only_marked_runs_and_their_rows(self, db, tmp_path):
        from topodb.ingest import _common as C

        # a run written by another session: no marker in params
        theirs = db.add_dataset(id="biology/rcsb_1crn", domain="biology", title="1CRN",
                                source="RCSB", provenance="observation")
        their_run = db.add_run(dataset_id=theirs, method="alpha", coeff_field=2, params={},
                               script="topodb_runs/biology/run_proteins.py", command="x", tier="X")
        db.add_bars(their_run, 1, [(0.0, 1.0)])
        db.add_statistic(their_run, "s", 1.0)
        db.add_control(their_run, "known_answer", "k", True)
        their_finding = db.add_finding(run_id=their_run, claim="theirs", verdict="recovered", tier="X")

        # a run written by this backfill, through Source, so it carries the marker
        src = C.Source(db, "test_source", "tdasimple")
        mine_ds = src.dataset(id="synthetic/mine", domain="synthetic", title="mine",
                              source="generated by a test", provenance="synthetic_control")
        my_run = src.run(dataset_id=mine_ds, method="alpha", coeff_field=2, params={"a": 1},
                         script="audit/x.py", command="x", tier="X")
        src.bars(my_run, 1, [(0.0, 2.0)])
        src.stat(my_run, "s", 2.0)
        src.control(my_run, "known_answer", "k", True)
        src.finding(run_id=my_run, claim="mine", verdict="recovered", tier="X")
        my_ds_finding = src.finding(dataset_id=mine_ds, claim="mine, dataset level",
                                    verdict="null", tier="X")
        assert json.loads(db.con.execute("SELECT params_json FROM run WHERE id=?",
                                         (my_run,)).fetchone()[0])["_backfill_source"] == "test_source"

        manifest = str(tmp_path / "owned.json")
        C.save_manifest(src.owned(), manifest)
        removed = C.wipe_owned(db, manifest)

        assert removed["runs"] == 1
        assert db.con.execute("SELECT count(*) FROM run").fetchone()[0] == 1
        assert db.con.execute("SELECT id FROM run").fetchone()[0] == their_run
        for t in ("bar", "statistic", "control"):
            rows = db.con.execute(f"SELECT run_id FROM {t}").fetchall()
            assert [r[0] for r in rows] == [their_run], t
        assert [r[0] for r in db.con.execute("SELECT id FROM finding")] == [their_finding]
        # api.add_finding indexes into the FTS table; the index must not outlive the row,
        # or `topodb.cli search` returns hits whose ref_id no longer resolves
        assert db.con.execute(
            "SELECT count(*) FROM search WHERE kind='finding' AND ref_id NOT IN "
            "(SELECT CAST(id AS TEXT) FROM finding)").fetchone()[0] == 0
        assert db.con.execute(
            "SELECT count(*) FROM search WHERE kind='dataset' AND ref_id NOT IN "
            "(SELECT id FROM dataset)").fetchone()[0] == 0
        assert [r["ref_id"] for r in db.search("theirs")] == [str(their_finding)]
        assert [r[0] for r in db.con.execute("SELECT id FROM dataset")] == [theirs]
        assert db.con.execute("SELECT 1 FROM finding WHERE id=?", (my_ds_finding,)).fetchone() is None

    def test_wipe_owned_keeps_a_dataset_another_session_still_uses(self, db, tmp_path):
        from topodb.ingest import _common as C

        shared = "synthetic/circle"
        src = C.Source(db, "test_source", "tdasimple")
        src.dataset(id=shared, domain="synthetic", title="circle", source="s",
                    provenance="synthetic_control")
        mine = src.run(dataset_id=shared, method="alpha", coeff_field=2, params={},
                       script="audit/x.py", command="x", tier="X")
        theirs = db.add_run(dataset_id=shared, method="rips", coeff_field=2, params={},
                            script="topodb_runs/x.py", command="x", tier="X")
        manifest = str(tmp_path / "owned.json")
        C.save_manifest(src.owned(), manifest)
        C.wipe_owned(db, manifest)
        assert db.con.execute("SELECT count(*) FROM dataset WHERE id=?", (shared,)).fetchone()[0] == 1
        assert [r[0] for r in db.con.execute("SELECT id FROM run")] == [theirs]
        assert mine not in [r[0] for r in db.con.execute("SELECT id FROM run")]

    def test_wipe_owned_sweeps_index_rows_left_by_an_earlier_reset(self, db, tmp_path):
        """An earlier reset that deleted findings without their index rows is repaired,
        and only rows whose target is already gone are touched."""
        from topodb.ingest import _common as C

        _dataset(db)
        live = db.add_finding(dataset_id="synthetic/circle", claim="still here",
                              verdict="null", tier="X")
        stale = db.add_finding(dataset_id="synthetic/circle", claim="orphan",
                               verdict="null", tier="X")
        db.con.execute("DELETE FROM finding WHERE id=?", (stale,))   # index row left behind
        db.con.commit()
        assert db.con.execute("SELECT count(*) FROM search WHERE kind='finding'").fetchone()[0] == 2

        removed = C.wipe_owned(db, str(tmp_path / "missing.json"))
        assert removed["orphan_search_rows_finding"] == 1
        assert [r["ref_id"] for r in db.con.execute(
            "SELECT ref_id FROM search WHERE kind='finding'")] == [str(live)]
        assert db.con.execute("SELECT count(*) FROM finding").fetchone()[0] == 1

    def test_wipe_owned_on_an_empty_manifest_deletes_nothing(self, db, tmp_path):
        from topodb.ingest import _common as C

        _dataset(db)
        r = _run(db)          # no marker: not ours
        db.add_bars(r, 1, [(0.0, 1.0)])
        removed = C.wipe_owned(db, str(tmp_path / "missing.json"))
        assert removed["runs"] == 0
        assert db.con.execute("SELECT count(*) FROM run").fetchone()[0] == 1
        assert db.con.execute("SELECT count(*) FROM bar").fetchone()[0] == 1
