#!/usr/bin/env python3
"""E-flux v3, script 03: TT section 4.1 family counted in the UNIMODULAR lattice.

Family (4.8)-(4.10): alpha_y=-beta_x, beta_y=alpha_x, alpha_x^2=beta_x^2>0, alpha_x.beta_x=0.
Flux vectors are 2*lambda with lambda in the lattice; write m = lambda^2 (even).  Then
alpha_x^2 = 4m, N_flux = 2*alpha_x^2 (4.13; checked from (2.8) in 02), N_D3 = 24 - N_flux/2 = 24 - 4m >= 0.

Usage:   <venv python> 03_family41_counts.py N6 N8
   N6 = max entry bound of the lambda-window for Gamma_{3,3} = U^3 (windows 1..N6 are all run)
   N8 = max entry bound for the rank-8 truncation Gamma_{3,3} + A2(-1) (first two E8 nodes of (A.4)); 0 = skip
Committed run:  cd audit/k3t2_rigidity_v3/E-flux/scripts && <venv python> 03_family41_counts.py 3 2

Counts are ORDERED pairs (alpha_x,beta_x) INSIDE the box |lambda coordinate| <= N.  'Modulo G' = number of orbits of the
finite group G (order 384) or G+ (order 192, det +1 on the positive block) on that window-set, by Burnside (the window is
G-invariant, asserted).  These are NOT counts of physically distinct vacua.  'O(3,3;Z)-generated components' = connected
components of the window-set under the generators GL(3,Z) elementary, B-shifts, block swaps, with edges kept only when both
ends stay in the window (an UPPER bound on the number of orbits of the generated subgroup); it is compared with a LOWER bound
from O(Gamma)-invariants (Smith/Hermite image of Gamma -> Z^2, x -> (x.lambda_a, x.lambda_b)).
"""
import sys, time, itertools, math
import numpy as np
import sympy as sp
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import connected_components
from common import *
from lattice_u3 import H33_np, group_G, orient_plus, in_D, is_isometry
from inputs_decl import TADPOLE_TOTAL, NFLUX_FACTOR_41, HALF

SCRIPT = "03_family41_counts.py"

def gram(rank):
    if rank == 6:
        return H33_np.copy()
    E8 = np.array(parse_E8())
    H = np.zeros((rank, rank), dtype=np.int64)
    H[:6, :6] = H33_np
    k = rank - 6
    H[6:, 6:] = -E8[:k, :k]
    return H

def window(rank, N):
    r = np.arange(-N, N + 1, dtype=np.int64)
    grids = np.meshgrid(*([r] * rank), indexing="ij")
    return np.stack([g.ravel() for g in grids], axis=1)

def gens_O33(rank):
    """generators of a subgroup of O(3,3;Z) (extended by identity on extra coordinates); coordinates (x1,y1,x2,y2,x3,y3,...)"""
    gens = []
    def I():
        return np.eye(rank, dtype=np.int64)
    X = lambda i: 2 * i
    Y = lambda i: 2 * i + 1
    for i in range(3):
        for j in range(3):
            if i != j:
                M = I(); M[X(i), X(j)] += 1; M[Y(j), Y(i)] -= 1   # x_i += x_j ; y_j -= y_i  (A=I+E_ij, A^{-T}=I-E_ji)
                gens.append(("GL3_E%d%d" % (i, j), M))
    for i in range(3):
        for j in range(i + 1, 3):
            M = I(); M[X(i), Y(j)] += 1; M[X(j), Y(i)] -= 1        # B-shift
            gens.append(("Bshift_%d%d" % (i, j), M))
    for i in range(3):
        M = I(); M[X(i), X(i)] = 0; M[Y(i), Y(i)] = 0; M[X(i), Y(i)] = 1; M[Y(i), X(i)] = 1
        gens.append(("swap_%d" % i, M))
    return gens

def hnf_image(cols):
    """Hermite normal form of the subgroup of Z^2 generated by the given integer 2-vectors -> (a,b,d) with basis (a,b),(0,d)."""
    vs = [tuple(int(x) for x in c) for c in cols if any(c)]
    # column reduction on second coordinate
    d = 0
    for _, q in vs:
        d = math.gcd(d, abs(q))
    if d == 0:
        return (math.gcd(*[abs(p) for p, _ in vs]) if vs else 0, 0, 0)
    # find combination with second coordinate = d and reduce first coordinate
    # extended gcd over the list
    g, coef = 0, [0] * len(vs)
    cur = (0, 0)
    for k, (p, q) in enumerate(vs):
        # combine cur and (p,q) to get gcd of second coordinates
        if q == 0:
            continue
        a, b = cur
        if b == 0:
            cur = (p, q) if q > 0 else (-p, -q)
        else:
            gg, s, t = ext_gcd(b, q)
            cur = (s * a + t * p, gg)
    a, b = cur
    # subgroup elements with second coord 0 contribute p-gcd
    pzero = 0
    for p, q in vs:
        pass
    # lattice = span{(a,d)} + {(p0,0)} where p0 = gcd of first coords of the second-coordinate-zero part of the lattice
    # compute exactly through sympy hermite via generic method
    M = sp.Matrix([[p for p, q in vs], [q for p, q in vs]])
    from sympy.matrices.normalforms import hermite_normal_form
    Hn = hermite_normal_form(M)
    Hn = [[int(x) for x in row] for row in Hn.tolist()]
    return tuple(tuple(r) for r in Hn)

def ext_gcd(a, b):
    if b == 0:
        return (abs(a), (1 if a >= 0 else -1), 0)
    g, s, t = ext_gcd(b, a % b)
    return (g, t, s - (a // b) * t)

def lattice_image_key(la, lb, H):
    """O(Gamma_{3,3})-invariant of the ORDERED pair: the subgroup {(x.la, x.lb): x in Z^r} of Z^2, via 2x2 minors' gcd
    and the gcds of each coordinate (a complete invariant of a rank-2 subgroup up to the ordered pair is its HNF; we
    use the HNF computed by sympy on the 2 x r matrix)."""
    ga = H @ la; gb = H @ lb
    return hnf_key(ga, gb)

_hnf_cache = {}
def hnf_key(ga, gb):
    """HNF of the column lattice of [ga; gb] (2 x r) -- computed by an explicit two-step gcd reduction (exact)."""
    cols = [(int(p), int(q)) for p, q in zip(ga, gb) if (p or q)]
    # reduce: lattice L in Z^2 generated by cols.  Compute d = gcd of q's ; then a = gcd of {p} over combos with q=0 ...
    # do Euclid on pairs
    basis_top = None
    rows = list(cols)
    # bring to echelon by repeated Euclid on second coordinate
    vecs = [list(c) for c in rows]
    pivot = None
    # collect gcd vector with second coordinate = d
    top = None
    rest = []
    for v in vecs:
        if top is None:
            if v[1] != 0:
                top = v[:]
            else:
                rest.append(v)
            continue
        # Euclid between top and v on second coordinate
        a, b = top, v[:]
        while b[1] != 0:
            q = a[1] // b[1]
            a = [a[0] - q * b[0], a[1] - q * b[1]]
            a, b = b, a
        top = a
        rest.append(b)     # b has second coord 0
    if top is not None and top[1] < 0:
        top = [-top[0], -top[1]]
    p0 = 0
    for v in rest:
        p0 = math.gcd(p0, abs(v[0]))
    if top is None:
        return (0, 0, p0)
    a = top[0] % p0 if p0 else top[0]
    return (a, top[1], p0)


CHUNK = 1500
PAIR_CAP = 3_000_000
SAMPLES = 1500

def count_pairs(S, Hn):
    """number of ordered pairs (i,j) with lambda_i . lambda_j = 0 (i.e. alpha_x.beta_x=0), chunked"""
    HS = S @ Hn
    tot = 0
    for a in range(0, len(S), CHUNK):
        tot += int(((S[a:a + CHUNK] @ HS.T) == 0).sum())
    return tot

def get_pairs(S, Hn):
    HS = S @ Hn
    out = []
    for a in range(0, len(S), CHUNK):
        D = S[a:a + CHUNK] @ HS.T
        p = np.argwhere(D == 0); p[:, 0] += a
        out.append(p)
    return np.concatenate(out) if out else np.zeros((0, 2), dtype=np.int64)

def vector_invariants(S, Hn):
    """Distinct values of a cheap O(Gamma)-invariant of the ordered pair (lambda_a,lambda_b), unimodular Gamma:
    (content(a), content(b), content(a+b), content(a-b), gcd of all 2x2 minors of [a;b]).  A LOWER-bound tool only (not complete)."""
    r = S.shape[1]
    idx = [(p, q) for p in range(r) for q in range(p + 1, r)]
    keys = set()
    HS = S @ Hn
    for a in range(0, len(S), CHUNK):
        D = S[a:a + CHUNK] @ HS.T
        pi, pj = np.nonzero(D == 0)
        if len(pi) == 0:
            continue
        A = S[a:a + CHUNK][pi]; B = S[pj]
        ca = np.gcd.reduce(np.abs(A), axis=1); cb = np.gcd.reduce(np.abs(B), axis=1)
        cp = np.gcd.reduce(np.abs(A + B), axis=1); cm = np.gcd.reduce(np.abs(A - B), axis=1)
        mg = np.zeros(len(A), dtype=np.int64)
        for p, q in idx:
            mg = np.gcd(mg, np.abs(A[:, p] * B[:, q] - A[:, q] * B[:, p]))
        K = np.stack([ca, cb, cp, cm, mg], axis=1)
        for k in np.unique(K, axis=0):
            keys.add(tuple(int(x) for x in k))
    return keys

def greedy_reduce(la, lb, gens_and_inv, max_iter=400):
    """apply group generators (and inverses) greedily to shrink the L1 size of the pair; returns reduced pair"""
    la = np.array(la); lb = np.array(lb)
    size = lambda a, b: int(np.abs(a).sum() + np.abs(b).sum())
    cur = size(la, lb)
    for _ in range(max_iter):
        best = None
        for M in gens_and_inv:
            na, nb = M @ la, M @ lb
            sz = size(na, nb)
            if sz < cur:
                cur = sz; best = (na, nb)
        if best is None:
            break
        la, lb = best
    return la, lb

def even_overlattices(m):
    """Number of even integral overlattices of M = diag(m,m) (Gram of lambda_a, lambda_b): subgroups H of (Z/m)^2 such that every
    element (a,b) has norm (a^2+b^2)/m in 2Z and all pairs have (a a'+b b')/m in Z.  Nikulin-type consistency check, not a derivation."""
    els = [(a, b) for a in range(m) for b in range(m)]
    def gen(gs):
        H = {(0, 0)}
        frontier = [(0, 0)]
        while frontier:
            x = frontier.pop()
            for g in gs:
                y = ((x[0] + g[0]) % m, (x[1] + g[1]) % m)
                if y not in H:
                    H.add(y); frontier.append(y)
        return frozenset(H)
    subs = set()
    for g1 in els:
        for g2 in els:
            subs.add(gen([g1, g2]))
    good = 0
    for Hs in subs:
        ok = all(((a * a + b * b) % (2 * m) == 0) for a, b in Hs) and all(((a * c + b * d) % m == 0) for a, b in Hs for c, d in Hs)
        good += int(ok)
    return good

def orbits_burnside(S, pairs_i, pairs_j, Gmats, rank, Hn, only_plus=None):
    """S: (n,rank) vectors; the pair set is {(i,j)} ordered.  Number of orbits under the group by Burnside; returns (order, orbits)."""
    total = 0
    order = 0
    for M in Gmats:
        Sg = S @ M.T
        fixed = np.all(Sg == S, axis=1)
        idx = np.nonzero(fixed)[0]
        # count ordered pairs among fixed vectors with dot 0 (norms equal automatically by S_m)
        if len(idx) == 0:
            order += 1; continue
        F = S[idx]
        total += count_pairs(F, Hn)
        order += 1
    assert total % order == 0, (total, order)
    return order, total // order

def main():
    N6 = int(sys.argv[1]); N8 = int(sys.argv[2]) if len(sys.argv) > 2 else 0
    CMD = rel_command(SCRIPT, " ".join(sys.argv[1:]))
    t_start = time.time()
    Gall = group_G()
    Gplus = [M for M in Gall if orient_plus(M)]
    out_windows = []
    known_keys = {}
    m_tad_max = TADPOLE_TOTAL // (NFLUX_FACTOR_41 * 2 * (HALF // 2)) if False else None
    # tadpole: N_D3 = TADPOLE_TOTAL - (NFLUX_FACTOR_41*alpha_sq)/HALF >= 0 with alpha_sq = 4 m
    def allowed_m(m):
        return TADPOLE_TOTAL - sp.Rational(NFLUX_FACTOR_41 * 4 * m, HALF) >= 0

    runs = [(6, n) for n in range(1, N6 + 1)] + [(8, n) for n in range(1, N8 + 1)]
    for rank, N in runs:
        t0 = time.time()
        Hn = gram(rank)
        V = window(rank, N)
        q = np.einsum("ij,jk,ik->i", V, Hn, V)
        # G acts on the first 6 coordinates, identity on the rest
        def ext(M):
            if rank == 6: return M
            E = np.eye(rank, dtype=np.int64); E[:6, :6] = M; return E
        Gr = [ext(M) for M in Gall]; Gpr = [ext(M) for M in Gplus]
        inv_ok = all(np.array_equal(np.sort((V @ M.T).view([("", V.dtype)] * rank).ravel()), np.sort(V.view([("", V.dtype)] * rank).ravel())) for M in Gr[:6])
        # exact G-invariance of the window
        entry = {"rank": rank, "N": N, "n_lattice_vectors_in_window": int(len(V)), "window_G_invariant_(6_sample_elements_checked_exactly)": bool(inv_ok)}
        per_m = {}
        ms = sorted(int(x) for x in set(q[q > 0].tolist()))
        for m in ms:
            S = V[q == m]
            n_pairs = count_pairs(S, Hn)
            pairs = get_pairs(S, Hn) if n_pairs <= PAIR_CAP else None
            info = {"n_vectors_of_norm_m": int(len(S)), "ordered_pairs": n_pairs,
                    "tadpole_allowed": bool(allowed_m(m)),
                    "alpha_x_sq": 4 * m, "N_flux": int(sp.Rational(NFLUX_FACTOR_41 * 4 * m)), "N_D3": str(TADPOLE_TOTAL - sp.Rational(NFLUX_FACTOR_41 * 4 * m, HALF))}
            if rank == 6:
                inD = np.array([in_D(tuple(v)) for v in S])
                info["ordered_pairs_in_A6_subfamily_(lambda in D)"] = count_pairs(S[inD], Hn) if inD.any() else 0
            if allowed_m(m) and n_pairs > 0:
                if n_pairs > 0:
                    o_G = orbits_burnside(S, None, None, Gr, rank, Hn)
                    o_Gp = orbits_burnside(S, None, None, Gpr, rank, Hn)
                    info["orbits_mod_G_(order,count)"] = list(o_G); info["orbits_mod_G_plus_(order,count)"] = list(o_Gp)
                    if rank == 6:
                        # same for the A6 subfamily: restrict S to D (G preserves D)
                        SD = S[inD]
                        if len(SD):
                            info["orbits_mod_G_of_A6_subfamily"] = list(orbits_burnside(SD, None, None, Gr, rank, Hn))
                            info["orbits_mod_G_plus_of_A6_subfamily"] = list(orbits_burnside(SD, None, None, Gpr, rank, Hn))
                # invariants (lower bound) and generated-subgroup components (upper bound), rank 6 only, capped
                if rank == 6 and inD.any():
                    pD = get_pairs(S[inD], Hn)
                    HSD = S[inD] @ Hn
                    if len(pD):
                        info["A6_subfamily_O(Gamma33)_classes_hit_(distinct_invariants)"] = len({hnf_key(HSD[i], HSD[j]) for i, j in pD})
                if rank == 6:
                    vi = vector_invariants(S, Hn)
                    info["cheap_invariants_distinct_(lower_bound,_all_pairs)"] = len(vi)
                    info["cheap_invariants_values"] = sorted(vi)
                if rank == 6 and pairs is not None:
                    keys = {}
                    a_idx, b_idx = pairs[:, 0], pairs[:, 1]
                    inv_set = set()
                    # hnf key depends on (H la, H lb); compute via cache on the vector-level gram images
                    # (vectorised: compute HNF per distinct pair only for a subsample if huge)
                    Hla = S @ Hn  # (n,r) rows H*lambda
                    uniq = pairs if n_pairs <= 400_000 else pairs[np.random.RandomState(0).choice(n_pairs, 400_000, replace=False)]
                    for i, j in uniq:
                        inv_set.add(hnf_key(Hla[i], Hla[j]))
                    info["O(Gamma33)_invariants_distinct_(lower_bound_on_orbits)"] = len(inv_set)
                    info["invariants_computed_on"] = "all pairs" if n_pairs <= 400_000 else "random 400000-pair subsample (lower bound only)"
                    if n_pairs <= 400_000:
                        known_keys.setdefault(m, set()).update(inv_set)
                    # components
                    key_of = {tuple(v): k for k, v in enumerate(S)}
                    Sn = len(S)
                    pair_key = a_idx.astype(np.int64) * Sn + b_idx.astype(np.int64)
                    order = np.argsort(pair_key); pk_sorted = pair_key[order]
                    edges_u, edges_v = [], []
                    # map each vector index to image index under generator (or -1)
                    svec = {tuple(v): k for k, v in enumerate(S)}
                    for name, M in gens_O33(rank):
                        assert is_isometry(M[:6, :6]) if rank == 6 else True
                        img = np.full(Sn, -1, dtype=np.int64)
                        SM = S @ M.T
                        for k in range(Sn):
                            img[k] = svec.get(tuple(SM[k]), -1)
                        ia, ib = img[a_idx], img[b_idx]
                        ok = (ia >= 0) & (ib >= 0)
                        tgt_key = ia[ok] * Sn + ib[ok]
                        pos = np.searchsorted(pk_sorted, tgt_key)
                        pos = np.clip(pos, 0, len(pk_sorted) - 1)
                        found = pk_sorted[pos] == tgt_key
                        src = np.nonzero(ok)[0][found]
                        edges_u.append(src); edges_v.append(order[pos[found]])
                    u = np.concatenate(edges_u); v = np.concatenate(edges_v)
                    g = coo_matrix((np.ones(len(u), dtype=np.int8), (u, v)), shape=(n_pairs, n_pairs))
                    ncomp, labels = connected_components(g, directed=False)
                    info["generated_subgroup_components_(upper_bound_on_orbits)"] = int(ncomp)
                    info["generators_used"] = [n for n, _ in gens_O33(rank)]
                    info["lower_eq_upper"] = bool(len(inv_set) == ncomp)
            if rank == 6 and allowed_m(m) and n_pairs > 0:
                rs = np.random.RandomState(12345)
                gl = [M for _, M in gens_O33(rank)]
                gl_all = gl + [np.rint(np.linalg.inv(M)).astype(np.int64) for M in gl]
                HS = S @ Hn
                reduced_keys = set(); max_entry = 0; nsamp = 0
                for _ in range(SAMPLES):
                    i = rs.randint(len(S)); zs = np.nonzero(HS @ S[i] == 0)[0]
                    if len(zs) == 0:
                        continue
                    j = zs[rs.randint(len(zs))]
                    la, lb = greedy_reduce(S[i], S[j], gl_all)
                    reduced_keys.add(hnf_key(Hn @ la, Hn @ lb)); max_entry = max(max_entry, int(max(np.abs(la).max(), np.abs(lb).max()))); nsamp += 1
                info["greedy_reduction_sample"] = {"samples": nsamp, "distinct_classes_after_reduction": len(reduced_keys), "max_abs_entry_after_reduction": max_entry,
                                                   "classes_subset_of_smaller_window_full_invariant_classes": (bool(reduced_keys <= known_keys[m]) if m in known_keys and N > 2 else None)}
            per_m[str(m)] = info
        # totals
        tot_all = sum(v["ordered_pairs"] for v in per_m.values())
        tot_tad = sum(v["ordered_pairs"] for k, v in per_m.items() if v["tadpole_allowed"])
        entry["per_m_(m=lambda^2)"] = per_m
        entry["total_pairs_WITHOUT_tadpole_bound_(negative_control)"] = tot_all
        entry["total_pairs_WITH_tadpole_bound"] = tot_tad
        entry["tadpole_allowed_m_values_found_by_scan"] = [int(k) for k, v in per_m.items() if v["tadpole_allowed"]]
        entry["alpha_x_sq_values_with_tadpole"] = [4 * int(k) for k, v in per_m.items() if v["tadpole_allowed"]]
        entry["N_D3_values_with_tadpole"] = sorted({v["N_D3"] for v in per_m.values() if v["tadpole_allowed"]})
        entry["seconds"] = round(time.time() - t0, 1)
        out_windows.append(entry)
        print(f"rank {rank} N={N}: with-tadpole pairs {tot_tad}, without {tot_all}, {entry['seconds']}s", flush=True)

    # odd-lattice control for the divisibility (perturbs evenness): allowed alpha^2 values in the family
    Hodd = np.diag([1, 1, 1, -1, -1, -1]).astype(np.int64)
    Vo = window(6, 2)
    qo = np.einsum("ij,jk,ik->i", Vo, Hodd, Vo)
    odd_vals = {}
    for m in sorted(int(x) for x in set(qo[qo > 0].tolist())):
        S = Vo[qo == m]
        D = S @ Hodd @ S.T
        if (D == 0).any() and allowed_m(m):
            odd_vals[4 * m] = int((D == 0).sum())
    even_vals = {4 * int(k): v["ordered_pairs"] for k, v in out_windows[0]["per_m_(m=lambda^2)"].items() if v["tadpole_allowed"]} if out_windows else {}
    res = [{"id": "E03a", "quantity": "TT section 4.1 family in unimodular Gamma_{3,3}: ordered pairs, N_D3 values, counts modulo G and G+ (window-restricted)",
            "computed": {"windows": out_windows,
                         "TADPOLE_TOTAL_read_from_declared_input": TADPOLE_TOTAL,
                         "truncation_statement": "every count is inside the stated window (rank, N); the tadpole does not bound entries (see E03b)",
                         "orbit_meaning": "orbits of the FINITE group G (or G+) on the window-set; NOT physically distinct vacua; NOT O(Gamma) orbits"},
            "shared_inputs": ["TT_H33_gram_A3", "TT_E8_cartan_A4", "flux_quantisation_even_coefficients", "sec41_conditions_4.8_4.10", "tadpole_total_24_eq2.3", "tadpole_half_factor_eq2.3", "group_G_definition", "window_bounds", "embedding_A6_into_U3"],
            "script": SCRIPT, "command": CMD}]
    grow_with = [(w["rank"], w["N"], w["total_pairs_WITH_tadpole_bound"]) for w in out_windows]
    grow_without = [(w["rank"], w["N"], w["total_pairs_WITHOUT_tadpole_bound_(negative_control)"]) for w in out_windows]
    res.append({"id": "E03b", "quantity": "negative control: growth of the count with the window, WITH and WITHOUT the tadpole bound",
                "computed": {"with_tadpole_(rank,N,pairs)": grow_with, "without_tadpole_(rank,N,pairs)": grow_without,
                             "with_tadpole_strictly_increasing_in_N_rank6": all(b[2] > a[2] for a, b in zip([g for g in grow_with if g[0] == 6], [g for g in grow_with if g[0] == 6][1:])),
                             "without_tadpole_strictly_increasing_in_N_rank6": all(b[2] > a[2] for a, b in zip([g for g in grow_without if g[0] == 6], [g for g in grow_without if g[0] == 6][1:])),
                             "meaning": "in indefinite signature the bound alpha_x^2 <= 24 does NOT bound the entries of lambda, so the with-tadpole count also grows with the window; "
                                        "finiteness of any reported number comes from the stated window (or from a quotient by an infinite duality group), not from the tadpole alone. "
                                        "Without the tadpole bound the set of admissible alpha_x^2 is unbounded (all m>0 in the window)."},
                "shared_inputs": ["window_bounds", "tadpole_total_24_eq2.3"], "script": SCRIPT, "command": CMD})
    res.append({"id": "E03c", "quantity": "admissible alpha_x^2 (tadpole scan) in the unimodular EVEN lattice versus the ODD unimodular control",
                "computed": {"even_lattice_U3_alpha_sq_values": sorted(even_vals), "odd_control_I33_alpha_sq_values_window_N=2": sorted(odd_vals),
                             "odd_control_is_HYPOTHETICAL": "I_{3,3} is not H^2(K3,Z)",
                             "N_D3_even": sorted({str(TADPOLE_TOTAL - sp.Rational(NFLUX_FACTOR_41 * a, HALF)) for a in even_vals}),
                             "N_D3_odd_control": sorted({str(TADPOLE_TOTAL - sp.Rational(NFLUX_FACTOR_41 * a, HALF)) for a in odd_vals})},
                "shared_inputs": ["flux_quantisation_even_coefficients", "tadpole_total_24_eq2.3", "tadpole_half_factor_eq2.3", "sec41_conditions_4.8_4.10"], "script": SCRIPT, "command": CMD})
    ovl = {str(m): even_overlattices(m) for m in (2, 4, 6)}
    cls = {}
    for w in out_windows:
        if w["rank"] != 6:
            continue
        cls[w["N"]] = {mm: (i.get("generated_subgroup_components_(upper_bound_on_orbits)"), i.get("O(Gamma33)_invariants_distinct_(lower_bound_on_orbits)")) for mm, i in w["per_m_(m=lambda^2)"].items() if i["tadpole_allowed"]}
    stable = None
    ns = sorted(cls)
    if len(ns) >= 2:
        last2 = [cls[n] for n in ns[-2:]]
        stable = last2[0] == last2[1] and all(v[0] is not None and v[0] == v[1] for v in last2[1].values() if v[0] is not None)
    res.append({"id": "E03d", "quantity": "orbit classes of the 4.1 family under O(Gamma_{3,3}) (windows N>=2): generated-subgroup components (upper bound) equal O(Gamma)-invariant classes (lower bound), stable in N",
                "computed": {"per_window_(m: (upper,lower))": {str(n): {k: list(v) for k, v in d.items()} for n, d in cls.items()}, "stable_and_tight_at_last_two_rank6_windows": stable,
                             "even_overlattices_of_diag(m,m)_for_m=2,4,6": ovl,
                             "meaning": "these are orbits of the subgroup of O(Gamma_{3,3}) generated by GL(3,Z), B-shifts and block swaps acting on Gamma_{3,3} = U^3 (upper bound = components inside the window; lower bound = O(Gamma_{3,3}) invariants); "
                                        "they are NOT orbits of O(Gamma_{3,19}) (which may identify more) and do not include S-duality/T2 dualities. The even-overlattice counts are a Nikulin-type consistency expectation (one orbit per overlattice if the gluing is unique), not a derivation.",
                             "total_classes_with_tadpole": (sum(v[0] for v in cls[ns[-1]].values() if v[0] is not None) if ns else None)},
                "shared_inputs": ["TT_H33_gram_A3", "flux_quantisation_even_coefficients", "sec41_conditions_4.8_4.10", "tadpole_total_24_eq2.3", "window_bounds"], "script": SCRIPT, "command": CMD})
    rig = [{"parameter_inserted": "the window bound N (nuisance) in the number of O(Gamma_{3,3})-orbit classes of the 4.1 family with alpha_x^2 <= 24",
            "selecting_condition": "none: nothing is selected; the count of classes is compared across windows N=2,3", "condition_uses_true_value": False,
            "solution_set": "the class counts per m (upper=lower) do not change between the last two rank-6 windows (E03d); finite-group orbit counts DO grow (E03a)",
            "classification": "INVARIANCE", "input_it_depends_on": "declared generators and the 24 (only through which m are admissible)",
            "negative_control": "orbit counts modulo the finite group G grow with N (E03a) -- the stability is a property of the large group O(Gamma), not of the counting method",
            "control_perturbs_same_parameter": True},
           {"parameter_inserted": "the discrete set {N_D3} = {16, 8, 0} (equivalently alpha_x^2 in {8,16,24})",
            "selecting_condition": "N_D3 = 24 - N_flux/2 >= 0 with N_flux = 2 alpha_x^2 and alpha_x^2 in 8Z; the 24 is a typed literature input",
            "condition_uses_true_value": True,
            "solution_set": "{16, 8, 0} for even Gamma; odd control gives more values (E03c)",
            "classification": "CONDITIONAL_ON_INPUT",
            "input_it_depends_on": "tadpole_total_24_eq2.3 (tier L) -- changing 24 changes the set; the 8-divisibility itself is RIGID_GIVEN_DEFINITION (01)",
            "negative_control": "odd unimodular lattice changes the admissible alpha_x^2 set (E03c); removing the tadpole gives unbounded alpha_x^2 (E03b)",
            "control_perturbs_same_parameter": False,
            "note": "N_flux = 2*alpha_x^2 uses the typed 2 of (4.13) (also derived from (2.8) in 02 for the (4.8) family, so that factor is checked, not assumed)"}]
    write_json("03_family41_counts.json", {"script": SCRIPT, "results": res, "rigidity": rig, "literature_checks": [], "could_not_do": [], "wall_seconds": round(time.time() - t_start, 1)})
    print("done", round(time.time() - t_start, 1))

if __name__ == "__main__":
    main()
