"""STEP 0 -- known-answer control of this pipeline, before any biological data.

Three cases, all through the SAME helpers (bio_common.rips_from_points /
rips_from_distance / alpha_from_points) that every later run uses:

  A. noisy circle, n=200, radius 1, sigma 0.05   -> b1 = 1 with a DOMINANT H1 bar
  B. delay-embedded sine (tau, m=3)              -> dominant H1 loop
  C. uniform random cloud in the unit cube       -> NO dominant H1 (negative control)
  D. same circle via rips_from_distance on its own Euclidean matrix
     -> must agree with A (guards the distance-matrix path)

Pre-stated pass rule (written before running, see expectations.json):
  A passes if dominance(H1) >= 5 and the number of infinite-free H1 bars with
  persistence >= half the longest is exactly 1.
  B passes if dominance(H1) >= 5.
  C passes if dominance(H1) < 2.
  D passes if |dominance_D - dominance_A| / dominance_A < 1e-6.

If any of these fails, the whole biology block stops.

Seed: 20260920 everywhere.
"""
from __future__ import annotations

import sys
import time

import numpy as np

sys.path.insert(0, "/mnt/disks/disk-socrateai-local-1/wt-topo-bio/topodb_runs/biology")
from bio_common import (Block, alpha_from_points, betti_from_bars, dominance,  # noqa: E402
                        max_pers, rips_from_distance, rips_from_points, top_bars)

SEED = 20260920
SCRIPT = "topodb_runs/biology/step0_known_answer.py"
COMMAND = ("timeout 600 prlimit --as=8589934592 -- "
           "/home/callensxavier_gmail_com/SocrateAI-Scientific-DualScaleSimulator/.venv-tda/bin/python "
           "topodb_runs/biology/step0_known_answer.py")


def noisy_circle(n=200, sigma=0.05, rng=None):
    rng = rng or np.random.default_rng(SEED)
    th = rng.uniform(0, 2 * np.pi, n)
    return np.c_[np.cos(th), np.sin(th)] + rng.normal(0, sigma, (n, 2))


def delay_embed(x, tau, m):
    n = len(x) - (m - 1) * tau
    return np.c_[tuple(x[i * tau:i * tau + n] for i in range(m))]


def main() -> int:
    blk = Block("step0_known_answer", SCRIPT, COMMAND)
    rng = np.random.default_rng(SEED)
    verdicts = {}

    # ---- A: noisy circle, Rips on coordinates ------------------------------
    pts = noisy_circle(200, 0.05, rng)
    t = time.time()
    dg = rips_from_points(pts, max_hom_dim=1, max_edge=2.5)
    wall_a = round(time.time() - t, 2)
    domA = dominance(dg[1])
    p1 = max_pers(dg[1])
    n_big = sum(1 for b, d in dg[1] if np.isfinite(d) and (d - b) >= 0.5 * p1)
    okA = domA >= 5 and n_big == 1
    verdicts["A_noisy_circle"] = {"dominance": round(domA, 4), "n_bars_ge_half": n_big,
                                  "b0": betti_from_bars(dg[0]), "passed": bool(okA)}
    blk.dataset(id="synthetic/circle_noisy_n200", domain="synthetic",
                title="Noisy circle, n=200, r=1, sigma=0.05", source=f"generated by {SCRIPT}",
                provenance="synthetic_control", n_objects=200, ambient_dim=2, units="arbitrary",
                notes="Step 0 known-answer control: b1 must be 1 with a dominant H1 bar.")
    blk.run(dataset_id="synthetic/circle_noisy_n200", method="rips", coeff_field=2, max_dim=1,
            params={"max_edge_length": 2.5, "max_hom_dim": 1, "metric": "euclidean_coordinates",
                    "n": 200, "sigma": 0.05, "radius": 1.0},
            preprocessing="none", seed=SEED, tier="X", wall_sec=wall_a,
            diagrams=dg, betti={1: n_big, 0: betti_from_bars(dg[0])}, expected_betti={1: 1, 0: 1},
            stats=[{"name": "h1_dominance_P1_over_P2", "value": domA},
                   {"name": "h1_max_persistence", "value": p1}],
            controls=[{"kind": "known_answer", "description":
                       "noisy circle must give exactly one dominant H1 bar (dominance >= 5)",
                       "passed": bool(okA), "detail": f"dominance {domA:.3f}, {n_big} bars >= P1/2"}],
            findings=[{"claim": "Rips on a noisy circle recovers b1 = 1 with a dominant H1 bar.",
                       "verdict": "recovered" if okA else "failed", "tier": "X",
                       "caveat": "synthetic control, not data"}])

    # ---- D: same circle through the distance-matrix path -------------------
    from scipy.spatial.distance import squareform, pdist
    D = squareform(pdist(pts))
    t = time.time()
    dgD = rips_from_distance(D, max_hom_dim=1, max_edge=2.5)
    wall_d = round(time.time() - t, 2)
    domD = dominance(dgD[1])
    okD = abs(domD - domA) / max(domA, 1e-12) < 1e-6
    verdicts["D_distance_matrix_path"] = {"dominance": round(domD, 4), "passed": bool(okD)}
    blk.run(dataset_id="synthetic/circle_noisy_n200", method="rips", coeff_field=2, max_dim=1,
            params={"max_edge_length": 2.5, "max_hom_dim": 1, "metric": "precomputed_euclidean",
                    "n": 200},
            preprocessing="pairwise Euclidean distance matrix of the same 200 points",
            seed=SEED, tier="X", wall_sec=wall_d, diagrams=dgD,
            betti={1: sum(1 for b, d in dgD[1] if np.isfinite(d) and (d - b) >= 0.5 * max_pers(dgD[1]))},
            expected_betti={1: 1},
            stats=[{"name": "h1_dominance_P1_over_P2", "value": domD}],
            controls=[{"kind": "known_answer", "description":
                       "distance-matrix Rips must reproduce the coordinate Rips exactly",
                       "passed": bool(okD), "detail": f"coords {domA:.6f} vs matrix {domD:.6f}"}],
            findings=[{"claim": "rips_from_distance agrees with rips_from_points on the same cloud.",
                       "verdict": "recovered" if okD else "failed", "tier": "X"}])

    # ---- B: delay-embedded sine -------------------------------------------
    fs, f0, dur = 200.0, 3.0, 4.0
    tt = np.arange(0, dur, 1 / fs)
    x = np.sin(2 * np.pi * f0 * tt) + 0.02 * rng.normal(size=tt.size)
    tau = int(round(fs / f0 / 4))  # quarter period
    emb = delay_embed(x, tau, 3)
    idx = rng.choice(emb.shape[0], size=min(300, emb.shape[0]), replace=False)
    emb_s = emb[np.sort(idx)]
    t = time.time()
    dgB = rips_from_points(emb_s, max_hom_dim=1, max_edge=3.0)
    wall_b = round(time.time() - t, 2)
    domB = dominance(dgB[1])
    okB = domB >= 5
    verdicts["B_delay_embedded_sine"] = {"dominance": round(domB, 4), "tau": tau, "passed": bool(okB)}
    blk.dataset(id="synthetic/sine_delay_embedding", domain="synthetic",
                title="Delay embedding (m=3, tau=T/4) of a 3 Hz sine at 200 Hz, 2% noise",
                source=f"generated by {SCRIPT}", provenance="synthetic_control",
                n_objects=int(emb_s.shape[0]), ambient_dim=3, units="arbitrary",
                notes="Step 0: a periodic signal must give a dominant H1 loop.")
    blk.run(dataset_id="synthetic/sine_delay_embedding", method="rips", coeff_field=2, max_dim=1,
            params={"max_edge_length": 3.0, "max_hom_dim": 1, "m": 3, "tau_samples": tau,
                    "fs_hz": fs, "f0_hz": f0, "noise_sd": 0.02, "subsample_n": int(emb_s.shape[0]),
                    "metric": "euclidean_coordinates"},
            preprocessing=f"delay embedding m=3 tau={tau}; random subsample to {emb_s.shape[0]} points",
            seed=SEED, tier="X", wall_sec=wall_b, diagrams=dgB,
            betti={1: sum(1 for b, d in dgB[1] if np.isfinite(d) and (d - b) >= 0.5 * max_pers(dgB[1]))},
            expected_betti={1: 1},
            stats=[{"name": "h1_dominance_P1_over_P2", "value": domB}],
            controls=[{"kind": "known_answer", "description":
                       "delay-embedded periodic signal must give a dominant H1 loop (dominance >= 5)",
                       "passed": bool(okB), "detail": f"dominance {domB:.3f}"}],
            findings=[{"claim": "Delay embedding of a sine gives a dominant H1 loop.",
                       "verdict": "recovered" if okB else "failed", "tier": "X"}])

    # ---- C: random cloud, negative control ---------------------------------
    blob = rng.uniform(0, 1, (200, 3))
    t = time.time()
    dgC = rips_from_points(blob, max_hom_dim=1, max_edge=1.0)
    wall_c = round(time.time() - t, 2)
    domC = dominance(dgC[1])
    okC = domC < 2
    verdicts["C_random_cloud"] = {"dominance": round(domC, 4), "passed": bool(okC)}
    blk.dataset(id="synthetic/uniform_cube_n200", domain="synthetic",
                title="Uniform random cloud in the unit cube, n=200",
                source=f"generated by {SCRIPT}", provenance="synthetic_control",
                n_objects=200, ambient_dim=3, units="arbitrary",
                notes="Step 0 negative control: no dominant H1 expected.")
    blk.run(dataset_id="synthetic/uniform_cube_n200", method="rips", coeff_field=2, max_dim=1,
            params={"max_edge_length": 1.0, "max_hom_dim": 1, "n": 200,
                    "metric": "euclidean_coordinates"},
            preprocessing="none", seed=SEED, tier="X", wall_sec=wall_c, diagrams=dgC,
            stats=[{"name": "h1_dominance_P1_over_P2", "value": domC}],
            controls=[{"kind": "negative", "description":
                       "uniform random cloud must NOT show a dominant H1 (dominance < 2)",
                       "passed": bool(okC), "detail": f"dominance {domC:.3f}"}],
            findings=[{"claim": "A uniform random cloud shows no dominant H1 loop.",
                       "verdict": "null" if okC else "artefact", "tier": "X"}])

    # ---- alpha path sanity on the same circle (Euclidean, so legitimate) ----
    dgA2 = alpha_from_points(pts, max_hom_dim=1)
    domA2 = dominance(dgA2[1])
    verdicts["alpha_circle_dominance"] = round(domA2, 4)
    blk.run(dataset_id="synthetic/circle_noisy_n200", method="alpha", coeff_field=2, max_dim=1,
            params={"max_hom_dim": 1, "metric": "euclidean_coordinates",
                    "filtration": "sqrt of alpha^2"},
            preprocessing="none", seed=SEED, tier="X", diagrams=dgA2,
            stats=[{"name": "h1_dominance_P1_over_P2", "value": domA2}],
            controls=[{"kind": "known_answer",
                       "description": "alpha on the same Euclidean circle also gives a dominant H1",
                       "passed": bool(domA2 >= 5), "detail": f"dominance {domA2:.3f}"}],
            findings=[{"claim": "Alpha (legitimate here: genuinely Euclidean) also recovers the circle loop.",
                       "verdict": "recovered" if domA2 >= 5 else "failed", "tier": "X"}])

    print("\n".join(f"{k}: {v}" for k, v in verdicts.items()))
    all_ok = okA and okB and okC and okD
    print(f"STEP0 {'PASS' if all_ok else 'FAIL'}")
    blk.write()
    import json as _j
    from bio_common import RESULTS
    (RESULTS / "step0_verdicts.json").write_text(_j.dumps(
        {"verdicts": verdicts, "all_passed": bool(all_ok), "seed": SEED}, indent=1))
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
