"""DATASET 2: the 2-D XY model across temperatures, L = 32, 64, 128.

Vortex point clouds are recomputed here from the stored phase configurations by
plaquette phase winding (qf_lib.winding_vortices, periodic), NOT taken from the
earlier run's cached TDA files.

Alpha persistence on the vortex point cloud per temperature, against a
uniform-random null at the same count.

A lower-star statistic is also computed (b0 of the sublevel set of cos(theta)
at threshold 0, per site) and carries the MANDATORY site-shuffle control: the
earlier run measured that this path fails a site-shuffle control on rough
fields, and that limit is binding here.

Non-TDA cross-check recorded in the dataset notes (measured by the earlier run,
not re-derived): helicity-modulus crossing T_Ups = 0.9279 (L=32), 0.9147
(L=64), 0.9108 (L=128), extrapolating as T_inf + c/(ln L)^2 to 0.8915 against
the published T_BKT = 0.89289.

Run: prlimit --as=8589934592 -- .venv-tda/bin/python compute_xy.py
"""
import os

import numpy as np

import qf_lib as q

SEED = 20260920
N_CONFIG = 100
N_NULL = 200
TEMPS = [0.400, 0.700, 0.850, 0.900, 0.950, 1.000, 1.200, 1.600]
LS = [32, 64, 128]
SHUFFLE_T = [0.400, 0.900, 1.600]


def cloud_stats(pts, L, a_ref):
    if len(pts) < 4:
        return None
    bars = q.alpha_bars(pts, (3 * a_ref) ** 2)
    d0, d1 = q.h0_deaths(bars), q.h1_deaths(bars)
    p6, _ = q.psi6_global(pts)
    return {"h0_median": float(np.median(d0)) if d0.size else None,
            "h0_iqr_over_median": q.spread_stats(d0)["iqr_over_median"],
            "psi6": p6, "n": int(len(pts)),
            "betti": q.betti_from_bars(bars, 0.55 * a_ref),
            "bars": bars}


def main():
    assert q.assert_alpha_convention()
    rng = np.random.default_rng(SEED)
    out = {"meta": {"seed": SEED, "n_config": N_CONFIG, "n_null": N_NULL,
                    "command": q.command(), "script": os.path.abspath(__file__),
                    "vortex_detector": "plaquette phase winding, periodic, charge = round(circ/2pi)",
                    "source": "Wolff single-cluster Monte Carlo, J=1, generated by "
                              "audit/tda_validation/quantum_fluid/scripts/xy_mc.py (earlier run), "
                              "seeds 20260919 + 1000L + round(1000T)",
                    "helicity_crosscheck_not_recomputed": {
                        "T_Ups": {"32": 0.9279001427040815, "64": 0.9146922460319451,
                                  "128": 0.9108133517663207},
                        "T_inf_extrapolated": 0.8915464169432099,
                        "T_BKT_published": 0.89289}},
           "by_L": {}}

    for L in LS:
        rec = {}
        for T in TEMPS:
            fn = os.path.join(q.DATA_ROOT, f"xy/L{L}/T{T:.3f}.npz")
            if not os.path.exists(fn):
                print("MISSING", fn); continue
            z = np.load(fn)
            cfg = z["configs"][:N_CONFIG]
            per = []
            for th in cfg:
                pos, chg = q.winding_vortices(np.asarray(th, float), periodic=True)
                if len(pos) < 4:
                    per.append({"n": int(len(pos)), "psi6": None, "h0_median": None,
                                "h0_iqr_over_median": None, "b0": None, "b1": None})
                    continue
                nv = len(pos)
                a_ref = float(np.sqrt(2.0 / (np.sqrt(3.0) * nv / (L * L))))
                s = cloud_stats(pos, L, a_ref)
                per.append({"n": nv, "psi6": s["psi6"], "h0_median": s["h0_median"],
                            "h0_iqr_over_median": s["h0_iqr_over_median"],
                            "b0": s["betti"][0], "b1": s["betti"][1], "a_ref": a_ref})
            def med(k):
                v = np.array([p[k] for p in per if p.get(k) is not None], float)
                return float(np.median(v)) if v.size else None
            n_med = med("n")
            if n_med is None or n_med < 4:
                rec[f"{T:.3f}"] = {"T": T, "n_vortices_median": n_med,
                                   "note": "too few vortices for alpha persistence"}
                print(f"L={L} T={T:.3f} n={n_med} (skipped TDA)", flush=True)
                continue
            a_ref = float(np.sqrt(2.0 / (np.sqrt(3.0) * n_med / (L * L))))
            nul = {"psi6": [], "h0_iqr_over_median": []}
            for _ in range(N_NULL):
                rp = rng.random((int(n_med), 2)) * L
                s = cloud_stats(rp, L, a_ref)
                nul["psi6"].append(s["psi6"]); nul["h0_iqr_over_median"].append(s["h0_iqr_over_median"])
            obs = {"psi6": med("psi6"), "h0_iqr_over_median": med("h0_iqr_over_median")}
            pv = {"psi6": q.rank_p(obs["psi6"], nul["psi6"], "greater"),
                  "h0_iqr_over_median": q.rank_p(obs["h0_iqr_over_median"], nul["h0_iqr_over_median"], "less")}
            # bars from the first usable config
            pos0, _ = q.winding_vortices(np.asarray(cfg[0], float), periodic=True)
            b0 = cloud_stats(pos0, L, a_ref) if len(pos0) >= 4 else None
            rec[f"{T:.3f}"] = {
                "T": T, "n_vortices_median": n_med,
                "vortex_density_per_site": n_med / (L * L),
                "a_ref_from_density": a_ref,
                "h0_median": med("h0_median"),
                "observed": obs, "p_values_rank": pv, "n_null": N_NULL,
                "null_median": {k: float(np.median(v)) for k, v in nul.items()},
                "betti_median": {0: int(med("b0")), 1: int(med("b1"))},
                "top_h1_bars": q.top_bars(b0["bars"], 1, 10) if b0 else [],
                "top_h0_bars": q.top_bars(b0["bars"], 0, 10, r_trunc=3 * a_ref) if b0 else [],
            }
            print(f"L={L} T={T:.3f} nv={n_med:5.1f} rho={n_med/(L*L):.4f} psi6={obs['psi6']:.3f}"
                  f"(p={pv['psi6']:.4f},null={np.median(nul['psi6']):.3f}) "
                  f"iqr/med={obs['h0_iqr_over_median']:.3f}(p={pv['h0_iqr_over_median']:.4f},"
                  f"null={np.median(nul['h0_iqr_over_median']):.3f}) b={rec[f'{T:.3f}']['betti_median']}",
                  flush=True)

        # ---- MANDATORY site-shuffle control on the lower-star / cubical path
        sh = {}
        for T in SHUFFLE_T:
            fn = os.path.join(q.DATA_ROOT, f"xy/L{L}/T{T:.3f}.npz")
            if not os.path.exists(fn):
                continue
            cfg = np.load(fn)["configs"][:N_CONFIG]
            real, shuf = [], []
            srng = np.random.default_rng(SEED + L + int(1000 * T))
            for th in cfg:
                f = np.cos(np.asarray(th, float))
                bb = q.cubical_bars(f, sublevel=True)
                real.append(int(np.sum((bb[0][:, 0] <= 0.0) &
                                       (~np.isfinite(bb[0][:, 1]) | (bb[0][:, 1] > 0.0)))) / (L * L))
                fs = f.ravel().copy(); srng.shuffle(fs)
                bs = q.cubical_bars(fs.reshape(f.shape), sublevel=True)
                shuf.append(int(np.sum((bs[0][:, 0] <= 0.0) &
                                       (~np.isfinite(bs[0][:, 1]) | (bs[0][:, 1] > 0.0)))) / (L * L))
            r, s = np.array(real), np.array(shuf)
            se = np.sqrt(r.var(ddof=1) / r.size + s.var(ddof=1) / s.size)
            sh[f"{T:.3f}"] = {"real_b0_per_site": float(r.mean()), "shuffled_b0_per_site": float(s.mean()),
                              "diff_over_se": float((r.mean() - s.mean()) / se) if se > 0 else None,
                              "n_config": int(r.size),
                              "separates": bool(abs((r.mean() - s.mean()) / se) > 3) if se > 0 else None}
            print(f"  L={L} T={T:.3f} SHUFFLE lower-star b0/site real={r.mean():.5f} "
                  f"shuf={s.mean():.5f} diff/se={sh[f'{T:.3f}']['diff_over_se']:+.2f}", flush=True)
        out["by_L"][str(L)] = {"temperatures": rec, "site_shuffle_control": sh, "L": L}

    print("wrote", q.write_json("xy_vortex.json", out))


if __name__ == "__main__":
    main()
