"""DATASET 3: rotating-BEC Gross-Pitaevskii ground states at several rotation rates.

Two filtrations per rotation rate:
  (a) CUBICAL sublevel-set persistence of |psi|^2 inside the condensate mask.
      The vortex cores are the early local minima; the TDA core count is the
      number of H0 classes with persistence above a pre-stated threshold.
  (b) ALPHA persistence on the vortex-core point cloud.

The cross-check that makes this entry worth having: the cubical H0 core count is
compared against a plaquette phase-winding count recomputed HERE from psi. The
cached vortex_positions_*.npy files are deliberately NOT used.

The cubical path is morally lower-star on the pixel grid, so it carries the
MANDATORY site-shuffle control (inherited binding limit).

Data: generated by audit/tda_validation/quantum_fluid/scripts/gpe_rotating.py
(earlier run), seed 7, imaginary-time propagation to a stated mu tolerance.

Run: prlimit --as=8589934592 -- .venv-tda/bin/python compute_gpe.py
"""
import glob
import os

import numpy as np
from scipy import ndimage

import qf_lib as q

SEED = 20260920
N_NULL = 200
MASK_FRAC = 0.15        # condensate mask: smoothed |psi|^2 > MASK_FRAC * max
PERS_THRESH = 0.10      # cubical H0 persistence threshold, in units of max|psi|^2
BIG = 10.0              # value assigned outside the mask so it enters the filtration last


def core_count_cubical(f, mask, thresh=PERS_THRESH):
    g = np.where(mask, f, BIG)
    bars = q.cubical_bars(g, sublevel=True)
    iv = bars[0]
    if len(iv) == 0:
        return 0, iv
    dd = np.where(np.isfinite(iv[:, 1]), iv[:, 1], BIG)
    pers = dd - iv[:, 0]
    keep = (iv[:, 0] < BIG * 0.5) & (pers > thresh)
    return int(keep.sum()), iv[keep]


def main():
    assert q.assert_alpha_convention()
    rng = np.random.default_rng(SEED)
    files = sorted(glob.glob(os.path.join(q.DATA_ROOT, "gpe", "psi_Omega*.npz")))
    # prefer the _ext (further converged) file when both exist
    best = {}
    for f in files:
        b = os.path.basename(f)
        om = b.split("Omega")[1].split(".npz")[0].replace("_ext", "")
        if om not in best or "_ext" in b:
            best[om] = f
    out = {"meta": {"seed": SEED, "n_null": N_NULL, "mask_frac": MASK_FRAC,
                    "pers_thresh": PERS_THRESH, "command": q.command(),
                    "script": os.path.abspath(__file__),
                    "source": "generated by audit/tda_validation/quantum_fluid/scripts/gpe_rotating.py "
                              "(earlier run), seed 7",
                    "cubical": "sublevel-set persistence of |psi|^2/max inside the condensate mask; "
                               "cells outside the mask are set to %g so they enter last" % BIG,
                    "winding": "plaquette phase circulation of arg(psi), non-periodic, "
                               "charge = round(circ/2pi), restricted to the same mask"},
           "by_omega": {}}

    for om in sorted(best):
        z = np.load(best[om])
        psi = z["psi"]; x = z["x"]; Om = float(z["Omega"])
        dx = float(x[1] - x[0])
        rho = (np.abs(psi) ** 2).astype(float)
        rho /= rho.max()
        sm = ndimage.gaussian_filter(rho, 3.0)
        mask = sm > MASK_FRAC * sm.max()
        mask = ndimage.binary_erosion(mask, iterations=3)
        area = float(mask.sum()) * dx * dx

        n_cub, kept = core_count_cubical(rho, mask)

        # --- independent phase-winding count, recomputed here from psi
        th = np.angle(psi)
        pos, chg = q.winding_vortices(th, periodic=False)
        ij = np.rint(pos[:, ::-1]).astype(int)
        ij[:, 0] = np.clip(ij[:, 0], 0, mask.shape[0] - 1)
        ij[:, 1] = np.clip(ij[:, 1], 0, mask.shape[1] - 1)
        inside = mask[ij[:, 0], ij[:, 1]]
        pos_in, chg_in = pos[inside], chg[inside]
        n_wind = int(len(pos_in))
        n_wind_pos = int(np.sum(chg_in > 0))

        # --- alpha on the winding cores (physical units)
        pts = np.c_[x[0] + pos_in[:, 0] * dx, x[0] + pos_in[:, 1] * dx]
        rec = {"Omega": Om, "file": best[om], "sha256": q.sha256_file(best[om]),
               "grid": list(psi.shape), "dx": dx, "Lbox": float(z["Lbox"]),
               "mu": float(z["mu"]), "converged": bool(z["converged"]),
               "mask_area": area, "mask_cells": int(mask.sum()),
               "n_cores_cubical_H0": n_cub,
               "n_cores_phase_winding": n_wind,
               "n_winding_positive_charge": n_wind_pos,
               "crosscheck_difference": n_cub - n_wind,
               "crosscheck_agrees": bool(n_cub == n_wind)}

        if n_wind >= 4:
            a_ref = q.a_density(n_wind, area)
            bars = q.alpha_bars(pts, (3 * a_ref) ** 2)
            d0, d1 = q.h0_deaths(bars), q.h1_deaths(bars)
            p6, _ = q.psi6_global(pts)
            xmin, xmax = pts[:, 0].min(), pts[:, 0].max()
            ymin, ymax = pts[:, 1].min(), pts[:, 1].max()
            nul = {"psi6": [], "h0_iqr_over_median": []}
            for _ in range(N_NULL):
                # uniform random inside the mask, same count
                cand = rng.random((n_wind * 40, 2))
                cx = x[0] + cand[:, 0] * (mask.shape[1] * dx)
                cy = x[0] + cand[:, 1] * (mask.shape[0] * dx)
                ii = np.clip(((cy - x[0]) / dx).astype(int), 0, mask.shape[0] - 1)
                jj = np.clip(((cx - x[0]) / dx).astype(int), 0, mask.shape[1] - 1)
                ok = mask[ii, jj]
                rp = np.c_[cx[ok], cy[ok]][:n_wind]
                if len(rp) < 4:
                    continue
                bn = q.alpha_bars(rp, (3 * a_ref) ** 2)
                nul["psi6"].append(q.psi6_global(rp)[0])
                nul["h0_iqr_over_median"].append(q.spread_stats(q.h0_deaths(bn))["iqr_over_median"])
            obs = {"psi6": p6, "h0_iqr_over_median": q.spread_stats(d0)["iqr_over_median"]}
            rec.update({
                "a_density_nm_units": a_ref,
                "a_h1": float(np.sqrt(3) * np.median(d1)) if d1.size else None,
                "a_h0": float(2 * np.median(d0)) if d0.size else None,
                "observed": obs, "n_null": len(nul["psi6"]),
                "p_values_rank": {"psi6": q.rank_p(obs["psi6"], nul["psi6"], "greater"),
                                  "h0_iqr_over_median": q.rank_p(obs["h0_iqr_over_median"],
                                                                 nul["h0_iqr_over_median"], "less")},
                "null_median": {k: float(np.median(v)) for k, v in nul.items()},
                "betti_alpha": q.betti_from_bars(bars, 0.55 * a_ref),
                "top_h1_bars": q.top_bars(bars, 1, 10),
                "top_h0_bars": q.top_bars(bars, 0, 10, r_trunc=3 * a_ref),
            })

        # --- MANDATORY site-shuffle control on the cubical path
        srng = np.random.default_rng(SEED + int(round(Om * 100)))
        vals = rho[mask]
        shuf_counts = []
        for _ in range(20):
            v = vals.copy(); srng.shuffle(v)
            g2 = np.full(rho.shape, BIG); g2[mask] = v
            nc, _ = core_count_cubical(g2, mask)
            shuf_counts.append(nc)
        sc = np.array(shuf_counts, float)
        rec["site_shuffle_control"] = {
            "real_n_cores_cubical": n_cub,
            "shuffled_mean": float(sc.mean()), "shuffled_std": float(sc.std(ddof=1)),
            "n_shuffles": int(sc.size),
            "diff_over_se": float((n_cub - sc.mean()) / (sc.std(ddof=1) / np.sqrt(sc.size)))
                            if sc.std(ddof=1) > 0 else None,
            "separates": bool(abs(n_cub - sc.mean()) > 3 * sc.std(ddof=1)) if sc.std(ddof=1) > 0 else None,
            "note": "site-shuffle destroys the spatial arrangement while preserving the value histogram; "
                    "the cubical core count must not survive it",
        }
        out["by_omega"][f"{Om:.2f}"] = rec
        print(f"Omega={Om:.2f} cubical H0 cores={n_cub}  winding cores={n_wind} "
              f"(diff {n_cub-n_wind:+d}) psi6={rec.get('observed',{}).get('psi6', float('nan')):.3f} "
              f"shuffle real={n_cub} shuf={sc.mean():.1f}+-{sc.std(ddof=1):.1f} "
              f"separates={rec['site_shuffle_control']['separates']}", flush=True)

    print("wrote", q.write_json("gpe_vortex.json", out))


if __name__ == "__main__":
    main()
