"""
=============================================================================
LeanFlow: Authentic 4D N=1 Supergravity Moduli Potentials & Weil-Petersson Geodesics
=============================================================================
Replaces flat Cartesian Landau-Ginzburg double-wells with the exact supergravity
F-term potential generated by:
1. Gukov-Vafa-Witten (GVW) flux superpotential:
       W_GVW(tau, U) = int_X (F_3 - tau H_3) ^ Omega(U)
2. Non-perturbative gaugino condensation / D3-instantons:
       W_np(T) = A * exp(-a * T)
3. Tree-level Kahler potential on Calabi-Yau / Kummer moduli space:
       K = -ln(-i(tau - tau_bar)) - 3 ln(-i(U - U_bar)) - 2 ln(V_E(T))
4. Curved Weil-Petersson / Poincare metric and Christoffel connections:
       G_{A, B_bar} = d_A d_{B_bar} K
=============================================================================
"""

import math
from dataclasses import dataclass
from typing import Tuple, Dict, Any, Optional
import numpy as np

try:
    import torch
    TORCH_AVAILABLE = True
except ImportError:
    TORCH_AVAILABLE = False


@dataclass
class SupergravityParameters:
    """Parameters defining the 4D N=1 supergravity flux compactification."""
    # Flux integers for GVW superpotential: W_flux = (a0 - tau*b0) + (a1 - tau*b1)*U
    a0: float = 2.0
    b0: float = 1.0
    a1: float = -1.0
    b1: float = 2.0
    # Non-perturbative volume stabilization parameters (KKLT / gaugino condensation)
    A_np: float = 1.0
    a_np: float = 0.2 * math.pi  # a = 2*pi / N
    # Anti-D3 brane uplift coefficient
    c_uplift: float = 0.05
    # Planck mass scale
    m_pl: float = 1.0


class SupergravityModuli:
    """
    Evaluates authentic 4D N=1 Supergravity scalar potentials and Weil-Petersson
    kinetic geometry on Calabi-Yau / Kummer moduli space.
    """
    def __init__(self, params: Optional[SupergravityParameters] = None):
        self.params = params or SupergravityParameters()

    def kahler_potential(self, tau_im: float, u_im: float, sigma: float) -> float:
        """
        K = -ln(2*tau_im) - 3*ln(2*u_im) - 3*ln(2*sigma)
        where sigma = Re(T) controls the volume V = (2*sigma)^{3/2}.
        """
        if tau_im <= 0 or u_im <= 0 or sigma <= 0:
            return float("inf")
        return -math.log(2.0 * tau_im) - 3.0 * math.log(2.0 * u_im) - 3.0 * math.log(2.0 * sigma)

    def superpotential(self, tau: complex, u: complex, t: complex) -> complex:
        """
        W = W_GVW(tau, U) + W_np(T)
          = (a0 - tau*b0) + (a1 - tau*b1)*u + A*exp(-a*t)
        """
        p = self.params
        w_flux = (p.a0 - tau * p.b0) + (p.a1 - tau * p.b1) * u
        w_np = p.A_np * np.exp(-p.a_np * t)
        return complex(w_flux + w_np)

    def covariant_derivatives(
        self, tau: complex, u: complex, t: complex
    ) -> Tuple[complex, complex, complex, complex]:
        """
        Computes W and Kahler-covariant derivatives D_A W = d_A W + (d_A K)*W.
        Returns: (W, D_tau W, D_U W, D_T W)
        """
        p = self.params
        w = self.superpotential(tau, u, t)
        
        tau_im = tau.imag
        u_im = u.imag
        sigma = t.real

        if tau_im <= 0 or u_im <= 0 or sigma <= 0:
            raise ValueError("Moduli outside physical chamber (negative imaginary parts or volume)")

        # Kahler metric connections d_A K
        k_tau = 1.0j / (2.0 * tau_im)  # d/d_tau [-ln(-i(tau - tau_bar))] = i / (2*tau_im)
        k_u = 3.0j / (2.0 * u_im)
        k_t = -1.5 / sigma              # d/d_T [-3 ln(T + T_bar)] = -3 / (2*sigma)

        # Holomorphic derivatives d_A W
        dw_dtau = -p.b0 - p.b1 * u
        dw_du = p.a1 - tau * p.b1
        dw_dt = -p.a_np * p.A_np * np.exp(-p.a_np * t)

        d_tau_w = dw_dtau + k_tau * w
        d_u_w = dw_du + k_u * w
        d_t_w = dw_dt + k_t * w

        return w, d_tau_w, d_u_w, d_t_w

    def f_term_potential(
        self, tau: complex, u: complex, t: complex, include_uplift: bool = True
    ) -> float:
        """
        Evaluates the authentic F-term supergravity potential:
        V_F = e^K [ K^{A, Bbar} D_A W (D_B W)* - 3 |W|^2 ] + V_lift
        """
        tau_im = tau.imag
        u_im = u.imag
        sigma = t.real

        if tau_im <= 1e-4 or u_im <= 1e-4 or sigma <= 1e-4:
            return 1e6  # Steep repulsive boundary protecting chamber walls

        w, d_tau, d_u, d_t = self.covariant_derivatives(tau, u, t)
        
        k = self.kahler_potential(tau_im, u_im, sigma)
        exp_k = math.exp(k)

        # Inverse Kahler metrics K^{A, Bbar}
        k_inv_tau = 4.0 * (tau_im ** 2)
        k_inv_u = (4.0 / 3.0) * (u_im ** 2)
        k_inv_t = (4.0 / 3.0) * (sigma ** 2)

        # F-term kinetic sum
        f_norm = (
            k_inv_tau * (abs(d_tau) ** 2) +
            k_inv_u * (abs(d_u) ** 2) +
            k_inv_t * (abs(d_t) ** 2)
        )

        v_f = exp_k * (f_norm - 3.0 * (abs(w) ** 2))

        if include_uplift:
            # Anti-D3 brane positive uplift: V_lift = D / (2*sigma)^2
            v_lift = self.params.c_uplift / ((2.0 * sigma) ** 2)
            v_f += v_lift

        return float(v_f)

    def potential_derivatives_tau(
        self, tau: complex, u: complex, t: complex, eps: float = 1e-5
    ) -> Tuple[float, float, float]:
        """
        Computes V_F and its gradient with respect to axio-dilaton (tau_1, tau_2).
        Returns: (V, dV/d_tau1, dV/d_tau2)
        """
        v0 = self.f_term_potential(tau, u, t)
        v_tau1_plus = self.f_term_potential(tau + eps, u, t)
        v_tau1_minus = self.f_term_potential(tau - eps, u, t)
        dv_dtau1 = (v_tau1_plus - v_tau1_minus) / (2.0 * eps)

        v_tau2_plus = self.f_term_potential(tau + 1.0j * eps, u, t)
        v_tau2_minus = self.f_term_potential(tau - 1.0j * eps, u, t)
        dv_dtau2 = (v_tau2_plus - v_tau2_minus) / (2.0 * eps)

        return v0, dv_dtau1, dv_dtau2

    def weil_petersson_christoffel_tau(self, tau_im: float) -> Dict[Tuple[int, int, int], float]:
        """
        Computes the Christoffel connection Gamma^i_{jk} for the upper half-plane
        Poincare / Weil-Petersson metric:
        ds^2 = (d_tau1^2 + d_tau2^2) / (4 * tau2^2)
        
        Indices: 0 = tau1, 1 = tau2.
        Non-zero connections:
          Gamma^0_{01} = Gamma^0_{10} = -1 / tau2
          Gamma^1_{00} = +1 / tau2
          Gamma^1_{11} = -1 / tau2
        """
        if tau_im <= 0:
            raise ValueError("tau_im must be positive")
        inv_y = 1.0 / tau_im
        return {
            (0, 0, 1): -inv_y,
            (0, 1, 0): -inv_y,
            (1, 0, 0): inv_y,
            (1, 1, 1): -inv_y,
            (0, 0, 0): 0.0,
            (0, 1, 1): 0.0,
            (1, 0, 1): 0.0,
            (1, 1, 0): 0.0,
        }

    def geodesic_step_tau(
        self,
        tau: complex,
        v_tau: complex,
        u: complex,
        t: complex,
        dt: float,
        friction: float = 0.5
    ) -> Tuple[complex, complex]:
        """
        Integrates one curved geodesic step on Weil-Petersson moduli space:
        d^2 x^i / dt^2 + Gamma^i_{jk} (dx^j/dt)(dx^k/dt) + gamma (dx^i/dt) + G^{ij} dV/dx^j = 0
        """
        x1 = tau.real
        x2 = tau.imag
        v1 = v_tau.real
        v2 = v_tau.imag

        # Evaluate potential and gradient
        _, dv_dx1, dv_dx2 = self.potential_derivatives_tau(tau, u, t)

        # Inverse Poincare metric: G^{ij} = 4 * x2^2 * delta^{ij}
        g_inv = 4.0 * (x2 ** 2)
        force1 = -g_inv * dv_dx1
        force2 = -g_inv * dv_dx2

        # Christoffel connection forces: - Gamma^i_{jk} v^j v^k
        # Gamma^0: 2 * (-1/x2) * v1 * v2 = -2 * v1 * v2 / x2
        # Gamma^1: (1/x2) * v1^2 - (1/x2) * v2^2 = (v1^2 - v2^2) / x2
        geom_acc1 = (2.0 * v1 * v2) / x2
        geom_acc2 = -(v1 * v1 - v2 * v2) / x2

        # Net accelerations
        a1 = geom_acc1 + force1 - friction * v1
        a2 = geom_acc2 + force2 - friction * v2

        # Symplectic velocity verlet update
        v1_next = v1 + a1 * dt
        v2_next = v2 + a2 * dt

        x1_next = x1 + v1_next * dt
        x2_next = x2 + v2_next * dt

        # Prevent unphysical chamber penetration
        if x2_next < 1e-3:
            x2_next = 1e-3
            v2_next = abs(v2_next) * 0.5  # Elastic bounce with dissipation

        return complex(x1_next, x2_next), complex(v1_next, v2_next)


def evaluate_sugra_landscape_grid(
    n_points: int = 40,
    tau_re_bounds: Tuple[float, float] = (-1.0, 1.0),
    tau_im_bounds: Tuple[float, float] = (0.2, 2.5),
    u_fixed: complex = 1.0 + 1.2j,
    t_fixed: complex = 3.0 + 0.0j,
    params: Optional[SupergravityParameters] = None
) -> Dict[str, Any]:
    """
    Computes a 2D scalar potential landscape grid over the axio-dilaton plane.
    """
    sugra = SupergravityModuli(params)
    re_vals = np.linspace(tau_re_bounds[0], tau_re_bounds[1], n_points)
    im_vals = np.linspace(tau_im_bounds[0], tau_im_bounds[1], n_points)
    
    potential_grid = np.zeros((n_points, n_points))
    for i, im in enumerate(im_vals):
        for j, re in enumerate(re_vals):
            tau = complex(re, im)
            v = sugra.f_term_potential(tau, u_fixed, t_fixed)
            potential_grid[i, j] = v

    return {
        "re_vals": re_vals,
        "im_vals": im_vals,
        "potential_grid": potential_grid,
        "min_potential": float(np.min(potential_grid)),
        "max_potential": float(np.max(potential_grid)),
        "params": sugra.params.__dict__
    }
