-- TopoDB: a queryable record of every persistent-homology computation this project trusts.
-- Design rules (from audit/tda_validation and the LeanFlow CLAUDE.md):
--   * every run records the exact script, command, seed and input hash;
--   * every run records its evidence tier and whether a known-answer control passed;
--   * a p-value may only be stored together with the null it came from;
--   * nothing is stored as "verified" that a control did not check.
PRAGMA journal_mode=WAL;

CREATE TABLE IF NOT EXISTS dataset (
  id            TEXT PRIMARY KEY,           -- e.g. 'astro/desi_dr1_bgs_ngc'
  domain        TEXT NOT NULL CHECK (domain IN ('astro','quantum_fluid','biology','mathematics','synthetic')),
  title         TEXT NOT NULL,
  source        TEXT NOT NULL,              -- URL, DOI, archive id, or 'generated by <script>'
  provenance    TEXT NOT NULL CHECK (provenance IN ('observation','experiment','simulation','synthetic_control')),
  n_objects     INTEGER,                    -- points, pixels, cells...
  ambient_dim   INTEGER,
  units         TEXT,
  sha256        TEXT,                       -- of the primary file, when there is one
  local_path    TEXT,
  notes         TEXT
);

CREATE TABLE IF NOT EXISTS run (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  dataset_id    TEXT NOT NULL REFERENCES dataset(id),
  method        TEXT NOT NULL,              -- 'alpha' | 'rips' | 'sparse_rips' | 'witness' | 'cubical' | 'lower_star_graph' | 'chain_complex'
  coeff_field   INTEGER NOT NULL,           -- 2, 3, 5, 0 for rational/exact
  max_dim       INTEGER,
  params_json   TEXT NOT NULL,              -- all hyperparameters, explicitly
  preprocessing TEXT,                       -- subsampling, smoothing, embedding; the honest description
  script        TEXT NOT NULL,
  command       TEXT NOT NULL,
  seed          TEXT,
  git_commit    TEXT,
  branch        TEXT,
  wall_sec      REAL,
  peak_mb       REAL,
  tier          TEXT NOT NULL CHECK (tier IN ('A','B','L','C','X')),
  created       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS betti (
  run_id        INTEGER NOT NULL REFERENCES run(id),
  dim           INTEGER NOT NULL,
  value         INTEGER NOT NULL,           -- Betti number, when the run yields one
  expected      INTEGER,                    -- pre-stated expectation, when there is one
  matches       INTEGER,                    -- 1/0/NULL
  PRIMARY KEY (run_id, dim)
);

CREATE TABLE IF NOT EXISTS bar (
  run_id        INTEGER NOT NULL REFERENCES run(id),
  dim           INTEGER NOT NULL,
  birth         REAL NOT NULL,
  death         REAL,                       -- NULL = infinite
  rank          INTEGER                     -- 1 = longest in that dimension
);
CREATE INDEX IF NOT EXISTS bar_run ON bar(run_id, dim, rank);

CREATE TABLE IF NOT EXISTS statistic (
  run_id        INTEGER NOT NULL REFERENCES run(id),
  name          TEXT NOT NULL,              -- 'iqr_over_median', 'count', 'psi6', 'total_persistence', ...
  value         REAL NOT NULL,
  null_model    TEXT,                       -- REQUIRED for p_value: what the null was
  n_null        INTEGER,
  p_value       REAL,
  p_method      TEXT,                       -- 'rank' | 'chi2' | NULL
  multiplicity  TEXT,                       -- correction applied, if any
  PRIMARY KEY (run_id, name)
);

CREATE TABLE IF NOT EXISTS control (
  run_id        INTEGER NOT NULL REFERENCES run(id),
  kind          TEXT NOT NULL CHECK (kind IN ('known_answer','negative','null_calibration','shuffle','injection')),
  description   TEXT NOT NULL,
  passed        INTEGER,                    -- 1/0/NULL(not run)
  detail        TEXT,
  PRIMARY KEY (run_id, kind, description)
);

CREATE TABLE IF NOT EXISTS finding (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id        INTEGER REFERENCES run(id),
  dataset_id    TEXT REFERENCES dataset(id),
  claim         TEXT NOT NULL,
  verdict       TEXT NOT NULL CHECK (verdict IN ('recovered','null','inconclusive','failed','artefact')),
  tier          TEXT NOT NULL CHECK (tier IN ('A','B','L','C','X')),
  caveat        TEXT,
  reference     TEXT                        -- report path or publication
);

-- full-text search over the human-readable parts
CREATE VIRTUAL TABLE IF NOT EXISTS search USING fts5(
  kind, ref_id, title, text, tokenize='porter'
);
