"""Backfill source (b2): TDA validation against published genetics/genomics topology.

Source worktree : dualscale-wt-tdaval, branch loop/tda-validation
Source files    : audit/tda_validation/genetics/{expectations.json,
                  expectations_addendum_ecoli.json, report.json, sanity_circle.json,
                  test1_u2os_results.json, test1_mesc_results.json,
                  test2_hic_results.json, test3_influenza_results.json,
                  posthoc_diagnostics.json, posthoc_check2.json}
Pre-registration: expectations.json, "written and committed ALONE before any
                  persistence or statistic is computed on the real data listed
                  here" (_meta.purpose), 2026-09-19, branch loop/tda-validation;
                  expectations_addendum_ecoli.json is a SEPARATE pre-registration
                  written after test 2 and before the E. coli computation.
Tier            : X for every observed number. The published claims the tests are
                  gated against are literature (tier L) and are quoted in the
                  dataset `source` field.

P-VALUES. This is the one source where a p-value and its null count sit in the
same file: `args.n_null`, `linear_null.n_null_alpha`, `own_null_n`,
`null_pooled_single_segment_site_bootstrap.n`. Each p-value is carried with that
count and with the null-model prose quoted from expectations.json. Two p-values
have their draw count only in a KEY NAME (`alpha_pc12_whitened_z0_null200`); they
come from posthoc_diagnostics.json, whose own NOTE reads "POST HOC, not
pre-stated in expectations.json; does not change any verdict", and they are
carried with n_null = 200 read from that key name, stated in `null_model`.

INFINITY. posthoc_diagnostics.json contains three bare `Infinity` literals
(P1_over_P2 of the noiseless synthetic ring and chain). Python's json accepts
them as float('inf'); `Source.stat` refuses non-finite values, so those three
ratios are skipped and recorded under `skipped`.
"""
from __future__ import annotations

import math

from . import _common as C

DIR = "audit/tda_validation/genetics"

ALPHA_STATS = ("n_points", "n_h1_bars", "n_h1_infinite_death", "r_trunc_used", "P1", "P2",
               "P1_over_P2", "R_rms", "S", "dominant_birth_over_death")
RIPS_STATS = ("n_points", "n_h1_bars", "n_h1_infinite_death", "P1", "P2", "P1_over_P2",
              "median_nn_distance", "S_rips")


def _alpha_block(src, rid, blk, stats=ALPHA_STATS, prefix=""):
    for k in stats:
        v = blk.get(k)
        if isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v):
            src.stat(rid, prefix + k, v)
        elif v is not None and isinstance(v, float):
            src.skip(f"genetics statistic {prefix + k} on run {rid}",
                     f"the source records a non-finite value ({v!r}); the database stores only "
                     "finite statistics, so it was not carried")
    src.bars(rid, 1, [(b[0], b[1]) for b in blk.get("top_h1_bars_birth_death") or []])
    if blk.get("betti_numbers_full_complex"):
        src.betti(rid, C.betti_map(blk["betti_numbers_full_complex"]))


def ingest(db) -> dict:
    src = C.Source(db, "b2_genetics", "tdaval")
    rep = C.load(src.rel(DIR, "report.json"))
    exp = C.load(src.rel(DIR, "expectations.json"))
    add = C.load(src.rel(DIR, "expectations_addendum_ecoli.json"))
    sanity = C.load(src.rel(DIR, "sanity_circle.json"))
    u2os = C.load(src.rel(DIR, "test1_u2os_results.json"))
    mesc = C.load(src.rel(DIR, "test1_mesc_results.json"))
    hic = C.load(src.rel(DIR, "test2_hic_results.json"))
    flu = C.load(src.rel(DIR, "test3_influenza_results.json"))
    ph1 = C.load(src.rel(DIR, "posthoc_diagnostics.json"))
    ph2 = C.load(src.rel(DIR, "posthoc_check2.json"))
    base = dict(pipeline_under_test=(exp.get("_meta") or {}).get("pipeline_under_test"),
                expectations_pre_registered=f"{DIR}/expectations.json (written "
                                            f"{(exp.get('_meta') or {}).get('written')}, branch "
                                            f"{(exp.get('_meta') or {}).get('branch')}, "
                                            "committed alone before any computation)",
                convention_split=(exp.get("_meta") or {}).get("convention_split"),
                branch=rep.get("branch"))

    # ------------------------------------------- sanity: the known answers
    did = "synthetic/genetics/sanity_circle_and_blob"
    src.dataset(id=did, domain="synthetic",
                title="known-answer sanity set: a noisy circle (n=200, sigma=0.05) and a Gaussian "
                      "blob (n=200)", source="generated by sanity_circle.py; a circle has one H1 "
                                             "class and a blob has none (tier L)",
                provenance="synthetic_control", n_objects=200, ambient_dim=2,
                local_path=f"{DIR}/sanity_circle.json")
    for label, blk, method in [
        ("circle_alpha", (sanity.get("circle_n200_sigma0.05_seed0") or {}).get("alpha"), "alpha"),
        ("circle_rips", (sanity.get("circle_n200_sigma0.05_seed0") or {}).get("rips"), "rips"),
        ("gaussian_blob_alpha", sanity.get("gaussian_blob_n200_seed1_alpha"), "alpha"),
    ]:
        if not isinstance(blk, dict):
            continue
        rid = src.run(dataset_id=did, method=method, coeff_field=2, max_dim=2,
                      params=dict(base, leg=f"sanity/{label}", criterion=sanity.get("criterion"),
                                  pipeline_file_sha256=sanity.get("pipeline_file_sha256")),
                      preprocessing=label, script=f"{DIR}/sanity_circle.py",
                      command=f"{DIR}/sanity_circle.py", tier="X",
                      seed="0" if "circle" in label else "1", wall_sec=blk.get("runtime_sec"))
        _alpha_block(src, rid, blk, ALPHA_STATS if method == "alpha" else RIPS_STATS)
        src.control(rid, "known_answer", str(sanity.get("criterion")),
                    sanity.get("passed") if "circle" in label else None,
                    detail=f"P1/P2 = {blk.get('P1_over_P2')}, P1 = {blk.get('P1')}"
                           + ("" if "circle" in label else
                              "; the blob is the negative half of the sanity pair and the source "
                              "records no separate pass flag for it"))
    src.finding(dataset_id=did, tier="X", verdict="recovered" if sanity.get("passed") else "failed",
                claim=f"the alpha pipeline recovers a single dominant H1 class on a noisy circle "
                      f"(P1/P2 = "
                      f"{((sanity.get('circle_n200_sigma0.05_seed0') or {}).get('alpha') or {}).get('P1_over_P2')}) "
                      f"and none on a Gaussian blob (P1/P2 = "
                      f"{(sanity.get('gaussian_blob_n200_seed1_alpha') or {}).get('P1_over_P2')})",
                caveat=str(sanity.get("criterion")), reference=f"{DIR}/report.json")

    # ------------------------------------------ test 1a/1b: the cell cycle
    for tag, res, exp_key, title, source_claim, n_obj in [
        ("u2os", u2os, "test_1a_cell_cycle_U2OS_FUCCI",
         "hU2OS FUCCI single-cell RNA-seq, cell-cycle genes, PCA-3 embedding",
         (exp.get("test_1a_cell_cycle_U2OS_FUCCI") or {}).get("published_claim"), None),
        ("mesc", mesc, "test_1b_cell_cycle_mESC_Buettner",
         "mESC-SMARTer single-cell RNA-seq (Buettner et al.), cell-cycle genes, PCA-3 embedding",
         (exp.get("test_1b_cell_cycle_mESC_Buettner") or {}).get("published_claim"), None),
    ]:
        e = exp.get(exp_key) or {}
        info = res.get("info") or {}
        did = f"biology/genetics/cell_cycle_{tag}"
        src.dataset(id=did, domain="biology", title=title,
                    source=str(source_claim)[:900] or "see expectations.json",
                    provenance="observation",
                    n_objects=info.get("n_cells_after_qc") or info.get("n_cells"),
                    ambient_dim=3, local_path=f"{DIR}/test1_{tag}_results.json",
                    notes=f"pre-stated operationalization: "
                          f"{str(e.get('our_topological_operationalization'))[:500]}")
        args = res.get("args") or {}
        obs = res.get("observed_alpha_pca3") or {}
        params = dict(base, leg=f"test1_{tag}/alpha_pca3", args=args, info=info,
                      pipeline_file_sha256=res.get("pipeline_file_sha256"),
                      pca_var_frac_top3=obs.get("pca_var_frac_top3"),
                      preprocessing_pre_stated=e.get("preprocessing"),
                      pass_rule=e.get("pass_rule"), criteria=res.get("criteria"))
        rid = src.run(dataset_id=did, method="alpha", coeff_field=2, max_dim=2, params=params,
                      preprocessing=str(e.get("preprocessing"))[:500],
                      script=f"{DIR}/test1_cellcycle.py",
                      command=f"{DIR}/test1_cellcycle.py --dataset {res.get('dataset', tag)}",
                      tier="X", seed="0", wall_sec=obs.get("runtime_sec"))
        _alpha_block(src, rid, obs)
        ng = res.get("null_gene_permutation") or {}
        p, n_null = ng.get("p_S"), ng.get("n_null") or args.get("n_null")
        src.stat(rid, "p_S_vs_gene_permutation_null", p, null_model=str(e.get("null")),
                 n_null=n_null, p_value=p, p_method="rank")
        src.stat(rid, "null_frac_P1_over_P2_ge_2", ng.get("null_frac_P1_over_P2_ge_2"))
        pc = res.get("positive_check_circular_correlation") or {}
        src.stat(rid, "rho_cc", pc.get("rho_cc"))
        src.stat(rid, "abs_rho_cc", pc.get("abs_rho_cc"))
        src.stat(rid, "p_rho_cc_label_permutation", pc.get("p_perm"),
                 null_model=str(e.get("positive_check")), n_null=pc.get("n_perm"),
                 p_value=pc.get("p_perm"), p_method="rank")
        crit = res.get("criteria") or {}
        src.control(rid, "known_answer", str(e.get("pass_rule"))[:400],
                    res.get("verdict") == "PASS",
                    detail=f"criteria: {crit}; verdict {res.get('verdict')}")
        neg = res.get("negative_control_random_noncc_genes") or {}
        d0 = neg.get("primary_draw0") or {}
        nrid = src.run(dataset_id=did, method="alpha", coeff_field=2, max_dim=2,
                       params=dict(params, leg=f"test1_{tag}/negative_control_draw0",
                                   pool_size=neg.get("pool_size"), n_draws=neg.get("n_draws")),
                       preprocessing=str(e.get("negative_control"))[:500],
                       script=f"{DIR}/test1_cellcycle.py",
                       command=f"{DIR}/test1_cellcycle.py --dataset {tag} (negative control)",
                       tier="X", seed=str(d0.get("seed")))
        _alpha_block(src, nrid, d0, stats=("P1_over_P2", "S", "abs_rho_cc"))
        pn = d0.get("p_S_vs_own_null")
        src.stat(nrid, "p_S_vs_own_null", pn, null_model=str(e.get("negative_control")),
                 n_null=d0.get("own_null_n"), p_value=pn, p_method="rank")
        src.stat(nrid, "frac_draws_P1_over_P2_ge_2", neg.get("frac_draws_P1_over_P2_ge_2"))
        src.stat(nrid, "median_abs_rho_cc_over_draws", neg.get("median_abs_rho_cc"))
        src.control(nrid, "negative",
                    "random non-cell-cycle genes give no dominant, significant loop",
                    crit.get("iii_negative_control_not_dominant_and_significant"),
                    detail=f"draw 0: P1/P2 = {d0.get('P1_over_P2')}, p = {pn}; "
                           f"fraction of 20 draws with P1/P2 >= 2: "
                           f"{neg.get('frac_draws_P1_over_P2_ge_2')}")
        rx = res.get("rips_crosscheck_full_dim") or {}
        rrid = src.run(dataset_id=did, method="rips", coeff_field=2, max_dim=1,
                       params=dict(params, leg=f"test1_{tag}/rips_crosscheck",
                                   n_sub=rx.get("n_sub"), sub_seed=rx.get("sub_seed")),
                       preprocessing="Rips cross-check on the full-dimensional data",
                       script=f"{DIR}/test1_cellcycle.py",
                       command=f"{DIR}/test1_cellcycle.py --dataset {tag} (rips cross-check)",
                       tier="X", seed=str(rx.get("sub_seed")), wall_sec=rx.get("runtime_sec"))
        _alpha_block(src, rrid, rx, stats=RIPS_STATS)
        pr = rx.get("p_S_rips")
        src.stat(rrid, "p_S_rips", pr, null_model=str(e.get("null")) + " (Rips cross-check null)",
                 n_null=rx.get("n_null") or args.get("n_rips_null"), p_value=pr, p_method="rank")
        if tag == "mesc":
            cd = res.get("continuity_diagnostic") or {}
            src.stat(rid, "continuity_p_tri", cd.get("p_tri"),
                     null_model="within-phase label permutation of the cell-cycle phase labels",
                     n_null=cd.get("within_phase_perm_n"), p_value=cd.get("p_tri"), p_method="rank")
            src.control(rid, "known_answer", str(cd.get("continuous_loop_rule")),
                        cd.get("continuous"),
                        detail=f"birth/death = {cd.get('dominant_birth_over_death')}, "
                               f"p_tri = {cd.get('p_tri')}")
        src.finding(run_id=rid, dataset_id=did, tier="X",
                    verdict="recovered" if res.get("verdict") == "PASS" else "failed",
                    claim=f"test 1{'a' if tag == 'u2os' else 'b'} ({tag}): verdict "
                          f"{res.get('verdict')}. The dominant H1 bar has P1/P2 = "
                          f"{obs.get('P1_over_P2')} (pre-stated threshold 2.0) and the scale-free "
                          f"statistic S = {obs.get('S')} has p = {p} against the "
                          f"{n_null}-draw gene-wise permutation null; the circular correlation is "
                          f"|rho_cc| = {pc.get('abs_rho_cc')} with permutation p = {pc.get('p_perm')}",
                    caveat=str(e.get("caveat_prestated") or e.get("cluster_vs_loop_caveat_prestated"))[:600],
                    reference=f"{DIR}/report.json")

    # ------------------------------------ test 2 / 2b: bacterial Hi-C
    e2 = exp.get("test_2_circular_bacterial_chromosome_HiC") or {}
    e2b = next((v for k, v in add.items() if k.startswith("test_2b")), {}) or {}
    args = hic.get("args") or {}
    ds_titles = {
        "caulo_full": ("biology/genetics/caulobacter_hic_full",
                       "C. crescentus NA1000 Hi-C contact matrix, full (circular chromosome)"),
        "caulo_cut_ter": ("biology/genetics/caulobacter_hic_cut_ter",
                          "C. crescentus Hi-C, internal control: chromosome cut at ter"),
        "caulo_cut_ori": ("biology/genetics/caulobacter_hic_cut_ori",
                          "C. crescentus Hi-C, internal control: chromosome cut at ori"),
        "gm12878_chr1q": ("biology/genetics/gm12878_chr1q_hic",
                          "GM12878 chr1q Hi-C, external control: a LINEAR chromosome arm"),
        "ecoli_full": ("biology/genetics/ecoli_3cseq_full",
                       "E. coli 3C-seq contact matrix, full (circular chromosome, addendum test 2b)"),
        "ecoli_cut_ter": ("biology/genetics/ecoli_3cseq_cut_ter",
                          "E. coli 3C-seq, internal control: chromosome cut at ter"),
    }
    for case, blk in (hic.get("cases") or {}).items():
        did, title = ds_titles.get(case, (f"biology/genetics/hic_{case}", case))
        is_ecoli = case.startswith("ecoli")
        e = e2b if is_ecoli else e2
        src.dataset(id=did, domain="biology", title=title,
                    source=str(e.get("published_claim") or e2.get("published_claim"))[:900],
                    provenance="observation",
                    n_objects=(blk.get("alpha_path_mds3") or {}).get("n_points"),
                    ambient_dim=3, local_path=f"{DIR}/test2_hic_results.json",
                    notes=f"distance convention: {hic.get('distance')}")
        ln = blk.get("linear_null") or {}
        null_prose = str(e.get("null") or e2.get("null"))
        for leg, method, sub, stats, n_null, p_key in [
            ("alpha_path_mds3", "alpha", blk.get("alpha_path_mds3"), ALPHA_STATS,
             ln.get("n_null_alpha") or args.get("n_null"), "p_S_alpha"),
            ("rips_full_matrix", "rips", blk.get("rips_full_matrix"), RIPS_STATS,
             ln.get("n_null_rips") or args.get("n_rips_null"), "p_S_rips"),
            ("alpha_path_mds3_exponent1_sensitivity", "alpha",
             blk.get("alpha_path_mds3_exponent1_sensitivity"),
             ("P1", "P2", "P1_over_P2", "S"), None, None),
        ]:
            if not isinstance(sub, dict):
                continue
            rid = src.run(dataset_id=did, method=method, coeff_field=2, max_dim=2,
                          params=dict(base, leg=f"test2/{case}/{leg}", case=case,
                                      distance=hic.get("distance"), args=args,
                                      pipeline_file_sha256=hic.get("pipeline_file_sha256"),
                                      deviations_from_expectations=hic.get("deviations_from_expectations"),
                                      mds_top3_eig=sub.get("mds_top3_eig"),
                                      mds_frac_negative_eig_mass=sub.get("mds_frac_negative_eig_mass"),
                                      sensitivity_only=(leg.endswith("sensitivity") or None),
                                      pass_rule=e.get("pass_rule") or e2.get("pass_rule")),
                          preprocessing=str(hic.get("distance")),
                          script=f"{DIR}/test2_hic.py", command=f"{DIR}/test2_hic.py --cases {case}",
                          tier="X", wall_sec=sub.get("runtime_sec"))
            _alpha_block(src, rid, sub, stats)
            if p_key and ln.get(p_key) is not None:
                src.stat(rid, p_key, ln.get(p_key), null_model=null_prose, n_null=n_null,
                         p_value=ln.get(p_key), p_method="rank")
                src.stat(rid, "powerlaw_slope_fit_N8_to_N2", ln.get("powerlaw_slope_fit_N8_to_N2"))
            if leg == "alpha_path_mds3":
                src.control(rid, "known_answer",
                            (e.get("pass_rule") or e2.get("pass_rule") or "")[:400],
                            blk.get("dominant_and_significant_alpha"),
                            detail=f"P1/P2 = {sub.get('P1_over_P2')}, p_S_alpha = "
                                   f"{ln.get('p_S_alpha')} against a {n_null}-draw linear-polymer null")
    for tag, blk, e in [("test2_caulobacter", hic.get("test2_caulobacter") or {}, e2),
                        ("test2b_ecoli", hic.get("test2b_ecoli") or {}, e2b)]:
        did = "biology/genetics/caulobacter_hic_full" if "caulo" in tag else "biology/genetics/ecoli_3cseq_full"
        src.finding(dataset_id=did, tier="X",
                    verdict="recovered" if blk.get("verdict") == "PASS" else "failed",
                    claim=f"{tag}: alpha-path verdict {blk.get('verdict')}, Rips cross-check verdict "
                          f"{blk.get('verdict_rips_crosscheck')}; criteria "
                          f"{blk.get('criteria_alpha_binding')}",
                    caveat=str(e.get("caveat_prestated") or "")[:400] +
                           " Deviations recorded by the source: "
                           + str(hic.get("deviations_from_expectations")),
                    reference=f"{DIR}/report.json")
    if (hic.get("test2b_ecoli") or {}).get("verdict") == "PASS" and \
            (hic.get("test2b_ecoli") or {}).get("verdict_rips_crosscheck") == "FAIL":
        src.note_discrepancy(
            "genetics test 2b (E. coli)",
            "the alpha path passes the pre-stated criteria (verdict PASS) while the Rips cross-check "
            "on the same matrix fails (verdict_rips_crosscheck FAIL); both are ingested as separate "
            "runs with their own statistics")

    # -------------------------------------- test 3: influenza reassortment
    e3 = exp.get("test_3_viral_evolution_influenza") or {}
    prep = flu.get("prep_info") or {}
    did = "biology/genetics/avian_influenza_genomes"
    src.dataset(id=did, domain="biology",
                title=f"{prep.get('n_sub')} avian influenza genomes, 8 segments, aligned per segment "
                      "and concatenated",
                source=str(e3.get("published_claim"))[:900], provenance="observation",
                n_objects=prep.get("n_sub"), local_path=f"{DIR}/test3_influenza_results.json",
                notes=f"pyfamsa {prep.get('pyfamsa_version')}, subsample seed {prep.get('seed_sub')}")
    concat_rips_run = None
    for label, blk in list((flu.get("single_segments") or {}).items()) + \
            [("concatenated_8_segments", flu.get("concatenated_8_segments") or {})]:
        for leg, method, sub in [("rips", "rips", blk),
                                 ("alpha_mds3", "alpha", blk.get("alpha_path_mds3"))]:
            if not isinstance(sub, dict):
                continue
            rid = src.run(dataset_id=did, method=method, coeff_field=2, max_dim=1,
                          params=dict(base, leg=f"test3/{label}/{leg}", segment=label,
                                      pipeline_file_sha256=flu.get("pipeline_file_sha256"),
                                      n_sub=prep.get("n_sub"), pass_rule=e3.get("pass_rule"),
                                      statistics_pre_stated=e3.get("statistics"),
                                      criteria=flu.get("criteria_rips_binding")),
                          preprocessing="Hamming distances between aligned sequences"
                                        + ("; classical MDS to 3-D" if leg == "alpha_mds3" else ""),
                          script=f"{DIR}/test3_influenza.py", command=f"{DIR}/test3_influenza.py",
                          tier="X", seed=str(prep.get("seed_sub")))
            if label == "concatenated_8_segments" and leg == "rips":
                # remembered, not looked up: the database is shared with other
                # sessions, so a SQL lookup could resolve to someone else's run
                concat_rips_run = rid
            _alpha_block(src, rid, sub, ("P1", "P2", "P1_over_P2", "S", "A_max_h1_persistence",
                                         "median_pdist", "B_n_h1_ge_0.005", "n_h1_bars",
                                         "n_h1_infinite_death"))
    nb = flu.get("null_pooled_single_segment_site_bootstrap") or {}
    target = concat_rips_run
    # the null count lives under the key `n`, not `n_null`, in this file
    src.stat(target, "p_A_concat_vs_pooled_single_segment_bootstrap", nb.get("p_A_concat"),
             null_model=str(e3.get("null")), n_null=nb.get("n"), p_value=nb.get("p_A_concat"),
             p_method="rank")
    src.control(target, "known_answer", str(e3.get("pass_rule"))[:400],
                flu.get("verdict") == "PASS", detail=str(flu.get("criteria_rips_binding")))
    src.finding(run_id=target, dataset_id=did, tier="X",
                verdict="recovered" if flu.get("verdict") == "PASS" else "failed",
                claim=f"test 3 (influenza reassortment): verdict {flu.get('verdict')}. The "
                      f"concatenated 8-segment genome has A = "
                      f"{(flu.get('concatenated_8_segments') or {}).get('A_max_h1_persistence')} with "
                      f"p = {nb.get('p_A_concat')} against the {nb.get('n')}-replicate pooled "
                      f"single-segment site-bootstrap null, and B_concat = "
                      f"{(flu.get('concatenated_8_segments') or {}).get('B_n_h1_ge_0.005')} exceeds "
                      "every single segment's B",
                caveat="the source records no Betti numbers for this test, only bar counts and the "
                       "A/B statistics; the alpha path is reported but the pre-stated criteria bind "
                       "on the Rips path",
                reference=f"{DIR}/report.json")

    # -------------------------------------------------- post-hoc diagnostics
    did_ph = "synthetic/genetics/posthoc_synthetic_contact_matrices"
    src.dataset(id=did_ph, domain="synthetic",
                title="post-hoc synthetic contact matrices: a noiseless ring and a noiseless chain",
                source="generated by posthoc_diagnostics.py", provenance="synthetic_control",
                ambient_dim=3, local_path=f"{DIR}/posthoc_diagnostics.json",
                notes=str(ph1.get("NOTE")))
    for name, blk in (ph1.get("hic") or {}).items():
        if not isinstance(blk, dict) or "alpha_mds3" not in blk:
            continue
        for leg, method in (("alpha_mds3", "alpha"), ("rips", "rips")):
            sub = blk.get(leg)
            if not isinstance(sub, dict):
                continue
            rid = src.run(dataset_id=did_ph, method=method, coeff_field=2, max_dim=2,
                          params=dict(base, leg=f"posthoc/{name}/{leg}", post_hoc=True,
                                      post_hoc_note=ph1.get("NOTE"),
                                      mds_frac_negative_eig_mass=blk.get("mds_frac_negative_eig_mass")),
                          preprocessing=f"post-hoc synthetic {name}",
                          script=f"{DIR}/posthoc_diagnostics.py",
                          command=f"{DIR}/posthoc_diagnostics.py", tier="X")
            _alpha_block(src, rid, sub, ("P1", "P2", "P1_over_P2", "S", "dominant_birth_over_death"))
            src.control(rid, "known_answer",
                        f"post-hoc: the noiseless {name.split('_')[1]} matrix "
                        f"{'does' if 'ring' in name else 'does not'} produce an H1 class",
                        None,
                        detail=f"P1/P2 = {sub.get('P1_over_P2')!r}; the source records this "
                               "diagnostic as POST HOC and it changes no verdict, so no pass flag "
                               "is stored")
    for tag, blk in (("u2os", ph1.get("u2os") or {}), ("mesc", ph1.get("mesc") or {})):
        did = f"biology/genetics/cell_cycle_{tag}"
        for variant in ("alpha_pca3_as_prestated", "alpha_pc12_z0", "alpha_pca3_whitened",
                        "alpha_pc12_whitened_z0"):
            sub = blk.get(variant)
            if not isinstance(sub, dict):
                continue
            rid = src.run(dataset_id=did, method="alpha", coeff_field=2, max_dim=2,
                          params=dict(base, leg=f"posthoc/{tag}/{variant}", post_hoc=True,
                                      post_hoc_note=ph1.get("NOTE"), embedding_variant=variant),
                          preprocessing=f"post-hoc embedding variant {variant}",
                          script=f"{DIR}/posthoc_diagnostics.py",
                          command=f"{DIR}/posthoc_diagnostics.py", tier="X")
            _alpha_block(src, rid, sub, ("P1", "P2", "P1_over_P2", "S", "dominant_birth_over_death"))
            if variant == "alpha_pc12_whitened_z0":
                nn = blk.get("alpha_pc12_whitened_z0_null200") or {}
                nm = ("a 200-draw null; the draw count is encoded only in the source key name "
                      "`alpha_pc12_whitened_z0_null200` and no null-model prose is given in the file, "
                      "which its own NOTE marks POST HOC")
                for pname in ("p_S", "p_P1_over_P2"):
                    src.stat(rid, f"posthoc_{pname}", nn.get(pname), null_model=nm, n_null=200,
                             p_value=nn.get(pname), p_method="rank")
        rp = blk.get("rips_pc12")
        if isinstance(rp, dict):
            rid = src.run(dataset_id=did, method="rips", coeff_field=2, max_dim=1,
                          params=dict(base, leg=f"posthoc/{tag}/rips_pc12", post_hoc=True,
                                      post_hoc_note=ph1.get("NOTE")),
                          preprocessing="post-hoc Rips on the first two principal components",
                          script=f"{DIR}/posthoc_diagnostics.py",
                          command=f"{DIR}/posthoc_diagnostics.py", tier="X",
                          wall_sec=rp.get("runtime_sec"))
            _alpha_block(src, rid, rp, RIPS_STATS)

    # ----------------------------------------- post-hoc Betti curves (check2)
    did_c = "synthetic/genetics/posthoc_betti_curves"
    src.dataset(id=did_c, domain="synthetic",
                title="post-hoc Betti-curve check: the sanity circle and the E. coli MDS-3 embedding",
                source="generated by posthoc_check2.py", provenance="synthetic_control",
                local_path=f"{DIR}/posthoc_check2.json", notes=str(ph2.get("NOTE")))
    for name in ("circle_n200_curves", "ecoli_mds3_curves"):
        blk = ph2.get(name) or {}
        rid = src.run(dataset_id=did_c, method="alpha", coeff_field=2, max_dim=2,
                      params=dict(base, leg=f"posthoc_check2/{name}", post_hoc=True,
                                  post_hoc_note=ph2.get("NOTE"), r_grid=blk.get("r_grid"),
                                  beta0=blk.get("beta0"), beta1=blk.get("beta1"),
                                  beta2=blk.get("beta2"), euler=blk.get("euler")),
                      preprocessing="Betti curves over a 21-point radius grid",
                      script=f"{DIR}/posthoc_check2.py", command=f"{DIR}/posthoc_check2.py",
                      tier="X")
        src.stat(rid, "max_beta1", blk.get("max_beta1"))
        src.control(rid, "known_answer",
                    "the dimension-1 Betti curve equals the corresponding Euler-characteristic "
                    "component",
                    blk.get("betti_curve_dim1_equals_euler_component"),
                    detail=f"max beta1 = {blk.get('max_beta1')} over the r grid")

    for d in hic.get("deviations_from_expectations") or []:
        src.skip("genetics test 2 deviation from the pre-registration", str(d))
    src.skip("genetics full persistence diagrams",
             "every alpha and Rips block commits at most the five longest H1 bars "
             "(top_h1_bars_birth_death); the full diagrams were not saved")
    src.skip("genetics posthoc_diagnostics.json non-finite ratios",
             "three P1_over_P2 values are the bare literal Infinity (the noiseless synthetic ring "
             "and chain); the database stores only finite statistics, so those three were not "
             "carried, while their bars and the rest of their block were")
    src.skip("genetics local_datasets_assessment.json",
             "an assessment of candidate local datasets rather than a persistent-homology run; "
             "report.json local_datasets_assessment records the verdict, and the file also contains "
             "bare NaN literals")
    for k, v in (rep.get("absent") or {}).items():
        src.skip(f"genetics: {k}", str(v)[:400])
    return src.report()
