"""Backfill source (b1): TDA validation against established quantum-fluid topology.

Source worktree : dualscale-wt-tdaval, branch loop/tda-validation
Source files    : audit/tda_validation/quantum_fluid/{expectations.json, report.json,
                  results/{calib_pipeline,gpe_tda,stm_vortex_tda,xy_analysis,
                            stm_psi6_variants,gpe_edge_trace,domain06_assessment}.json}
Pre-registration: expectations.json, "committed alone, before any computation"
                  (report.json `expectations_commit`: a0fd19a).
Tier            : report.json declares tests 1 and 2 to be simulations of
                  established theory and test 3 to use real published STM
                  measurements; every observed number here is numerics, so every
                  run is tier X. The published values the runs are compared
                  against are quoted in the dataset `source` (tier L) and in the
                  finding claims.

NO P-VALUES ANYWHERE. Exhaustive search over the seven result JSONs finds no
p_value, pvalue, n_null or null-model prose field. The nulls that do exist are
structural (`random_control.per_seed`, `E1e_shuffle.<T>.shuffled`,
`f_short_rand`) and the source reports only their means and a `diff_over_se`.
Every statistic from this source is therefore stored WITHOUT a p-value, and the
control rows record the comparison instead.

BARS. Only `top3_h0_bars` (three H0 bars) survives, in calib_pipeline.json and
gpe_tda.json. stm_vortex_tda.json and xy_analysis.json keep no bars at all.
"""
from __future__ import annotations

from . import _common as C

DIR = "audit/tda_validation/quantum_fluid"
RES = f"{DIR}/results"
SCRIPTS = f"{DIR}/scripts"


def _h0(src, rid, blk, prefix=""):
    for k in ("n", "median", "q1", "q3", "iqr_over_median", "mean", "cv"):
        if isinstance(blk, dict):
            src.stat(rid, f"{prefix}h0_{k}", blk.get(k))


def ingest(db) -> dict:
    src = C.Source(db, "b1_quantum_fluid", "tdaval")
    rep = C.load(src.rel(DIR, "report.json"))
    calib = C.load(src.rel(RES, "calib_pipeline.json"))
    gpe = C.load(src.rel(RES, "gpe_tda.json"))
    stm = C.load(src.rel(RES, "stm_vortex_tda.json"))
    xy = C.load(src.rel(RES, "xy_analysis.json"))
    edge = C.load(src.rel(RES, "gpe_edge_trace.json"))
    variants = C.load(src.rel(RES, "stm_psi6_variants.json"))
    dom06 = C.load(src.rel(RES, "domain06_assessment.json"))
    verdicts = rep.get("verdict_table") or {}
    base = dict(expectations_commit=rep.get("expectations_commit"),
                status_of_tests=rep.get("status_of_tests"),
                no_p_value_in_this_source="none of the seven quantum-fluid result JSONs records a "
                                          "p_value, an n_null or a null-model description; every "
                                          "statistic here is stored without a p-value")

    # ============================================== calibration (known answers)
    did = "synthetic/qf/calibration_lattices"
    src.dataset(id=did, domain="synthetic",
                title="calibration point sets: a perfect triangular lattice (a=1), two jittered "
                      "copies, and five matched Poisson sets in the same box",
                source="generated by calib_pipeline.py; the expected H0 and H1 death radii of a "
                       "perfect triangular lattice are a/2 and a/sqrt(3) (tier L, geometry)",
                provenance="synthetic_control", ambient_dim=2,
                local_path=f"{RES}/calib_pipeline.json")
    refs = (calib.get("alpha_path") or {}).get("reference_values") or {}
    for label, blk in (calib.get("alpha_path") or {}).items():
        if not isinstance(blk, dict) or "h0_death_stats" not in blk:
            continue
        params = dict(base, leg="calibration/alpha", label=blk.get("label", label),
                      reference_values=refs, n_points=blk.get("n_points"))
        rid = src.run(dataset_id=did, method="alpha", coeff_field=2, max_dim=1, params=params,
                      preprocessing=str(blk.get("label", label)),
                      script=f"{SCRIPTS}/calib_pipeline.py", command=f"{SCRIPTS}/calib_pipeline.py",
                      tier="X", seed=label)
        src.betti(rid, C.betti_map(blk.get("betti_at_truncation")))
        src.bars(rid, 0, [(b[0], b[1]) for b in blk.get("top3_h0_bars") or []])
        _h0(src, rid, blk.get("h0_death_stats"))
        for stat_name in ("h1_n_bars", "h1_median_death_over_median_h0_death"):
            src.stat(rid, stat_name, blk.get(stat_name))
        for key in ("h1_birth_stats", "h1_death_stats", "h1_persistence_stats"):
            for k, v in (blk.get(key) or {}).items():
                src.stat(rid, f"{key}_{k}", v)
        if label == "perfect_triangular_a1":
            hd = (blk.get("h0_death_stats") or {}).get("median")
            src.control(rid, "known_answer",
                        "perfect triangular lattice: the median H0 death radius is a/2 and the "
                        "median H1 death radius is a/sqrt(3)",
                        abs((hd or 0) - refs.get("a_over_2", 0)) < 1e-9 if hd is not None else None,
                        detail=f"median H0 death {hd} against a/2 = {refs.get('a_over_2')}; "
                               f"report.json calibration records "
                               f"{(rep.get('calibration') or {}).get('perfect_triangular_H0_death_over_a')} "
                               "and "
                               f"{(rep.get('calibration') or {}).get('perfect_triangular_H1_death_over_a')} "
                               "for H0 and H1 in units of a")
    pois = (calib.get("alpha_path") or {}).get("poisson_same_N_same_box_seeds11_15") or []
    for blk in pois:
        rid = src.run(dataset_id=did, method="alpha", coeff_field=2, max_dim=1,
                      params=dict(base, leg="calibration/poisson_null", label=blk.get("label"),
                                  n_points=blk.get("n_points")),
                      preprocessing="matched Poisson point set in the same box",
                      script=f"{SCRIPTS}/calib_pipeline.py", command=f"{SCRIPTS}/calib_pipeline.py",
                      tier="X", seed=str(blk.get("label")))
        src.betti(rid, C.betti_map(blk.get("betti_at_truncation")))
        src.bars(rid, 0, [(b[0], b[1]) for b in blk.get("top3_h0_bars") or []])
        _h0(src, rid, blk.get("h0_death_stats"))
        src.control(rid, "null_calibration",
                    "Poisson reference: the H0 death IQR/median of a structureless point set",
                    None,
                    detail=f"this set: {(blk.get('h0_death_stats') or {}).get('iqr_over_median')}; "
                           f"mean over the five Poisson seeds: "
                           f"{(calib.get('alpha_path') or {}).get('poisson_iqr_over_median_mean')}; "
                           f"report.json quotes {(rep.get('calibration') or {}).get('poisson_H0_iqr_over_median')}")
    lsp = calib.get("lower_star_path") or {}
    did_ls = "synthetic/qf/lower_star_calibration_torus"
    src.dataset(id=did_ls, domain="synthetic",
                title="periodic grid fields for the lower-star calibration: an 8/32/64 torus Euler "
                      "check and a Gaussian-dip field on a 64-torus",
                source="generated by calib_pipeline.py; a 2-torus has chi = 0 and K planted dips "
                       "give b0 = K at a threshold between the dips and the background (tier L)",
                provenance="synthetic_control", ambient_dim=2, local_path=f"{RES}/calib_pipeline.json")
    dips = lsp.get("gaussian_dips_torus64") or {}
    rid = src.run(dataset_id=did_ls, method="lower_star_graph", coeff_field=2, max_dim=1,
                  params=dict(base, leg="calibration/lower_star", torus_euler=lsp.get("torus_euler"),
                              K_dips=dips.get("K_dips"), abs_thresholds=dips.get("abs_thresholds"),
                              expected=dips.get("expected")),
                  preprocessing="sublevel filtration of a periodic grid field",
                  script=f"{SCRIPTS}/calib_pipeline.py", command=f"{SCRIPTS}/calib_pipeline.py",
                  tier="X")
    for i, thr in enumerate(dips.get("abs_thresholds") or []):
        src.stat(rid, f"b0_at_threshold_{thr}", (dips.get("b0") or [None] * 9)[i])
        src.stat(rid, f"b1_at_threshold_{thr}", (dips.get("b1") or [None] * 9)[i])
        src.stat(rid, f"chi_at_threshold_{thr}", (dips.get("chi") or [None] * 9)[i])
    for n, blk in (lsp.get("torus_euler") or {}).items():
        src.stat(rid, f"torus_{n}_chi", blk.get("chi"))
        src.stat(rid, f"torus_{n}_V", blk.get("V"))
        src.stat(rid, f"torus_{n}_E", blk.get("E"))
        src.stat(rid, f"torus_{n}_F", blk.get("F"))
    src.control(rid, "known_answer",
                "the periodic grid complex has Euler characteristic 0 at every grid size, and K "
                "planted Gaussian dips give b0 = K at the separating threshold",
                all((b or {}).get("chi") == 0 for b in (lsp.get("torus_euler") or {}).values()),
                detail=f"chi per grid size: "
                       f"{ {n: (b or {}).get('chi') for n, b in (lsp.get('torus_euler') or {}).items()} }; "
                       f"dips b0 = {dips.get('b0')} against expected {dips.get('expected')}; "
                       f"report.json records lower_star_dips_b0 = "
                       f"{(rep.get('calibration') or {}).get('lower_star_dips_b0')}")

    # ================================================== test 1: 2-D XY model
    t1 = rep.get("test1_xy_bkt") or {}
    for L, blk in (xy.get("tda") or {}).items():
        did = f"quantum_fluid/xy_model_L{L}"
        src.dataset(id=did, domain="quantum_fluid",
                    title=f"2-D XY model, J=1, periodic {L}x{L}, Wolff cluster Monte Carlo, "
                          f"29 temperatures 0.40-1.60",
                    source="expected T_BKT = 0.89289 (Komura & Okabe, JPSJ 81, 113001 (2012), "
                           "arXiv:1210.6116, beta_KT = 1.11996(6)); tier L",
                    provenance="simulation", n_objects=int(L) ** 2, ambient_dim=2,
                    local_path=f"{RES}/xy_analysis.json",
                    notes=str(t1.get("setup"))[:800])
        for window in ("window_A", "window_B", "window_C", "E1e_classifier_on_shuffled_windowA"):
            w = blk.get(window)
            if not isinstance(w, dict):
                continue
            shuffled = "shuffled" in window
            rid = src.run(dataset_id=did, method="lower_star_graph", coeff_field=2, max_dim=1,
                          params=dict(base, leg=f"test1_xy/{window}", L=int(L),
                                      window_low=w.get("window_low"), window_high=w.get("window_high"),
                                      n_T=blk.get("n_T"), n_cfg_per_T=blk.get("n_cfg_per_T"),
                                      trained_on_site_shuffled_fields=shuffled,
                                      extension_note=blk.get("E1e_classifier_on_shuffled_note")),
                          preprocessing=("lower-star persistence of theta on the periodic lattice; "
                                         "classifier trained on SITE-SHUFFLED fields" if shuffled else
                                         "lower-star persistence of theta on the periodic lattice"),
                          script=f"{SCRIPTS}/xy_tda_features.py",
                          command=f"{SCRIPTS}/xy_tda_features.py --L {L}", tier="X",
                          seed=str(t1.get("setup", ""))[:150])
            src.stat(rid, "T_TDA_crossover", w.get("T_TDA"))
            src.stat(rid, "T_TDA_boot_std", w.get("T_TDA_boot_std"))
            src.stat(rid, "classifier_test_accuracy", w.get("test_accuracy"))
            if window == "window_A":
                src.stat(rid, "T_BKT_reference_literature", xy.get("T_BKT_ref"))
                src.control(rid, "negative",
                            "E1e: the same classifier trained on SITE-SHUFFLED fields must NOT "
                            "reproduce the crossover",
                            verdicts.get("E1e_shuffle_control"),
                            detail=f"shuffled crossings by L: "
                                   f"{(t1.get('E1b_primary_lower_star_crossover') or {}).get('classifier_on_shuffled_T_TDA_by_L')}; "
                                   f"verdict on E1b: "
                                   f"{verdicts.get('E1b_lower_star_crossover')}")
                src.control(rid, "known_answer",
                            "E1c: changing the training window moves the crossover by less than the "
                            "pre-stated tolerance at L=64",
                            (t1.get("E1c_training_window_control") or {}).get("PASS_at_L64"),
                            detail=str((t1.get("E1c_training_window_control") or {}).get("note")))
        for T, blk2 in (blk.get("E1d_corr") or {}).items():
            pass  # per-temperature correlations are summarised in the finding below
    e1a = t1.get("E1a_helicity_crosscheck") or {}
    src.finding(dataset_id="quantum_fluid/xy_model_L128", tier="X", verdict="recovered",
                claim=f"E1a: the helicity-modulus crossover extrapolates to T_inf = {e1a.get('T_inf')} "
                      f"against the literature T_BKT = {e1a.get('reference_T_BKT')}",
                caveat=str(e1a.get("scope")), reference=f"{DIR}/report.json")
    e1b = t1.get("E1b_primary_lower_star_crossover") or {}
    src.finding(dataset_id="quantum_fluid/xy_model_L128", tier="X", verdict="artefact",
                claim=f"E1b: the lower-star TDA classifier crossover meets the pre-stated bracket/drift "
                      f"rule (T_TDA by L: {e1b.get('T_TDA_windowA_by_L')}), but a classifier trained on "
                      f"SITE-SHUFFLED fields reproduces it "
                      f"({e1b.get('classifier_on_shuffled_T_TDA_by_L')})",
                caveat=str(e1b.get("VERDICT")), reference=f"{DIR}/report.json")
    e1d = t1.get("E1d_vortex_betti_identity") or {}
    src.finding(dataset_id="quantum_fluid/xy_model_L64", tier="X", verdict="failed",
                claim=f"E1d: the pre-stated vortex-Betti identity fails; the median Spearman "
                      f"correlation between the vortex count and b0 over T in [0.70, 0.80] is "
                      f"{e1d.get('median_spearman_rho_T_0.70_0.80')}",
                caveat="the source reports no p-value for this correlation, so none is stored",
                reference=f"{DIR}/report.json")

    # ============================================ test 2: rotating BEC (GPE)
    t2 = rep.get("test2_rotating_bec") or {}
    for omega, blk in gpe.items():
        did = f"quantum_fluid/gpe_rotating_{omega}"
        src.dataset(id=did, domain="quantum_fluid",
                    title=f"2-D Gross-Pitaevskii ground state at {omega}, g=1000, 384^2 grid on "
                          f"[-12,12)^2, imaginary-time Strang split-step",
                    source="Feynman's rule n_v = m Omega / (pi hbar) for the vortex areal density "
                           "in a rotating condensate (tier L); expected lattice constant a_F from it",
                    provenance="simulation", n_objects=384 * 384, ambient_dim=2,
                    local_path=f"{RES}/gpe_tda.json",
                    notes=str(t2.get("setup"))[:800])
        params = dict(base, leg=f"test2_gpe/{omega}", Omega=blk.get("Omega"), g=blk.get("g"),
                      dx=blk.get("dx"), R_eff=blk.get("R_eff"), mu=blk.get("mu"),
                      converged=blk.get("converged"), steps=blk.get("steps"),
                      file=blk.get("file"), feynman=blk.get("feynman"),
                      post_hoc_keys=[k for k in blk if k.startswith("posthoc_")],
                      post_hoc_note="keys prefixed posthoc_ were not pre-stated; no expectation is "
                                    "recorded for them")
        rid = src.run(dataset_id=did, method="lower_star_graph", coeff_field=2, max_dim=1,
                      params=params, preprocessing="lower-star filtration of the density on the grid",
                      script=f"{SCRIPTS}/gpe_tda.py", command=f"{SCRIPTS}/gpe_tda.py --omega {omega}",
                      tier="X", seed="7")
        src.betti(rid, {0: blk.get("lower_star_b0_at_0.1n0"), 1: blk.get("lower_star_b1_at_0.1n0")})
        src.stat(rid, "N_winding_r_lt_0.7R", blk.get("N_winding_r<0.7R"))
        src.stat(rid, "E2a_diff_b0_minus_Nwinding", blk.get("E2a_diff_b0_minus_Nwinding"))
        for k in ("mu", "R_eff", "n0_TF", "max_density", "min_density_in_disk_over_n0", "steps"):
            src.stat(rid, k, blk.get(k))
        e = edge.get(omega) or {}
        for k, v in e.items():
            if k != "R_eff":
                src.stat(rid, "edge_" + k.replace(" ", ""), v)
        src.control(rid, "known_answer",
                    "E2a: the lower-star b0 of the density equals the winding-number vortex count "
                    "inside 0.7 R (pre-stated tolerance 1)",
                    abs(blk.get("E2a_diff_b0_minus_Nwinding") or 0) <= 1
                    if blk.get("E2a_diff_b0_minus_Nwinding") is not None else None,
                    detail=f"b0 = {blk.get('lower_star_b0_at_0.1n0')}, winding count = "
                           f"{blk.get('N_winding_r<0.7R')}, difference "
                           f"{blk.get('E2a_diff_b0_minus_Nwinding')}; vortex centres just outside "
                           f"the analysis disk: {e.get('n_vortex_centres_in_(0.7R, 0.7R+0.25]')}")
        alpha = blk.get("alpha")
        if isinstance(alpha, dict):
            arid = src.run(dataset_id=did, method="alpha", coeff_field=2, max_dim=1,
                           params=dict(params, leg=f"test2_gpe/{omega}/alpha"),
                           preprocessing="alpha complex on the detected vortex centres",
                           script=f"{SCRIPTS}/gpe_tda.py",
                           command=f"{SCRIPTS}/gpe_tda.py --omega {omega} (alpha path)", tier="X",
                           seed="7")
            src.betti(arid, C.betti_map(alpha.get("betti_at_truncation")))
            src.bars(arid, 0, [(b[0], b[1]) for b in alpha.get("top3_h0_bars") or []])
            _h0(src, arid, alpha.get("h0"))
            for k in ("h1_n", "n_interior", "h1_death_median", "a_TDA", "a_TDA_over_a_F",
                      "2median_h0_over_a_F", "psi6_interior_mean_abs"):
                src.stat(arid, k.replace("2median", "twice_median"), alpha.get(k))
            for k, v in (blk.get("feynman") or {}).items():
                src.stat(arid, "feynman_" + k.replace("<", "_lt_"), v)
            rc = blk.get("random_control") or {}
            per_seed = rc.get("per_seed") or []
            src.stat(arid, "random_control_h0_iqr_over_median_mean", rc.get("h0_iqr_over_median_mean"))
            src.stat(arid, "random_control_psi6_interior_mean", rc.get("psi6_interior_mean"))
            src.stat(arid, "random_control_n_seeds", len(per_seed) or None)
            src.control(arid, "negative",
                        f"E2d: a random point set of the same size has a much larger H0 death "
                        f"IQR/median and a smaller psi6 than the vortex lattice",
                        (alpha.get("h0") or {}).get("iqr_over_median") is not None and
                        rc.get("h0_iqr_over_median_mean") is not None and
                        (alpha.get("h0") or {}).get("iqr_over_median") < rc.get("h0_iqr_over_median_mean"),
                        detail=f"lattice IQR/median {(alpha.get('h0') or {}).get('iqr_over_median')} "
                               f"vs random mean {rc.get('h0_iqr_over_median_mean')} over "
                               f"{len(per_seed)} seeds; psi6 {alpha.get('psi6_interior_mean_abs')} vs "
                               f"{rc.get('psi6_interior_mean')}. The source reports no p-value for "
                               "this comparison, so none is stored.")
    for tag, verdict_key, claim in [
        ("E2a", "E2a_h0_equals_winding",
         "E2a: the lower-star b0 does not equal the winding count within the pre-stated tolerance "
         "at every Omega"),
        ("E2b", "E2b_feynman", "E2b: the central vortex density does not meet the pre-stated Feynman band"),
        ("E2c", "E2c_lattice_tda_rule", "E2c: the TDA lattice constant matches a_F within the pre-stated band"),
    ]:
        v = verdicts.get(verdict_key)
        blk2 = t2.get({"E2a": "E2a_h0_equals_winding", "E2b": "E2b_feynman",
                       "E2c": "E2c_lattice_tda"}[tag]) or {}
        src.finding(dataset_id="quantum_fluid/gpe_rotating_Omega0.80", tier="X",
                    verdict="recovered" if v is True else ("failed" if v is False else "inconclusive"),
                    claim=claim, caveat=str(blk2.get("note"))[:600] if blk2.get("note") else
                    "the rotating runs did not all converge within the pre-stated step cap; see the "
                    "dataset notes", reference=f"{DIR}/report.json")

    # ==================================== test 3: real Re6Zr STM vortex maps
    meta = stm.get("meta") or {}
    t3 = rep.get("test3_real_stm_re6zr") or {}
    for field, blk in (stm.get("fields") or {}).items():
        did = f"quantum_fluid/re6zr_stm_{field}"
        src.dataset(id=did, domain="quantum_fluid",
                    title=f"Re6Zr STS conductance maps at {field}, 460 mK, 20 successive "
                          f"{blk.get('channel')} maps",
                    source="Duhan et al., Nat. Commun. 16, 2100 (2025); Zenodo 10.5281/zenodo.14780459 "
                           "(CC-BY-4.0). Expected triangular lattice constant a_tri = 1.075 "
                           "sqrt(Phi0/B) (tier L)",
                    provenance="observation", n_objects=(blk.get("h0_pooled") or {}).get("n"),
                    ambient_dim=2, units="nm", local_path=f"{RES}/stm_vortex_tda.json",
                    notes=f"detector: {meta.get('detector')}; data root {meta.get('data_root')}")
        rid = src.run(dataset_id=did, method="alpha", coeff_field=2, max_dim=1,
                      params=dict(base, leg=f"test3_stm/{field}", H_kOe=blk.get("H_kOe"),
                                  B_T=blk.get("B_T"), a_tri_nm=blk.get("a_tri_nm"),
                                  pixel_nm=blk.get("pixel_nm"), scan_nm=blk.get("scan_nm"),
                                  n_images=blk.get("n_images"), channel=blk.get("channel"),
                                  detector=meta.get("detector"), Phi0_Wb=meta.get("Phi0_Wb")),
                      preprocessing=str(meta.get("detector")),
                      script=f"{SCRIPTS}/stm_vortex_tda.py",
                      command=f"{SCRIPTS}/stm_vortex_tda.py", tier="X")
        _h0(src, rid, blk.get("h0_pooled"), prefix="pooled_")
        for k in ("count_median", "expected_count_B_A_over_Phi0", "count_ratio_median",
                  "a_TDA_sqrt3_median_h1_death_nm", "a_TDA_over_a_tri",
                  "a_from_2_median_h0_over_a_tri", "psi6_global_mean", "psi6_global_std"):
            src.stat(rid, k, blk.get(k))
        rc = blk.get("random_control") or {}
        _h0(src, rid, rc.get("h0_pooled"), prefix="random_control_")
        src.stat(rid, "random_control_psi6_global_mean", rc.get("psi6_global_mean"))
        # post-hoc psi6 variants: the source's own `note` says POST-HOC, so no expectation is set
        for k, v in (variants.get("by_field") or {}).get(field, {}).items():
            if k != "n_images":
                src.stat(rid, "posthoc_psi6_" + k.replace(".", "_"), v)
        src.control(rid, "negative",
                    "E3e: a random point set of the same count has a far larger H0 death IQR/median "
                    "and a far smaller psi6",
                    verdicts.get("E3e_random_control"),
                    detail=f"data IQR/median {(blk.get('h0_pooled') or {}).get('iqr_over_median')} vs "
                           f"random {(rc.get('h0_pooled') or {}).get('iqr_over_median')}; psi6 "
                           f"{blk.get('psi6_global_mean')} vs {rc.get('psi6_global_mean')}. "
                           "No p-value is reported by the source, so none is stored.")
        if field == "20kOe":
            e3a = t3.get("E3a") or {}
            src.control(rid, "known_answer",
                        "E3a: the alpha-path lattice constant is within +/-10% of a_tri at 20 kOe",
                        e3a.get("PASS"),
                        detail=f"a_TDA = {e3a.get('a_TDA_nm')} nm against a_tri = "
                               f"{e3a.get('a_tri_nm')} nm, ratio "
                               f"{e3a.get('observed_a_TDA_over_a_tri_20kOe')}")
    e3b, e3c, e3d = t3.get("E3b") or {}, t3.get("E3c") or {}, t3.get("E3d") or {}
    src.finding(dataset_id="quantum_fluid/re6zr_stm_20kOe", tier="X", verdict="recovered",
                claim="E3a/E3b/E3c on real Re6Zr STM data: the alpha-path lattice constant matches "
                      "a_tri at 20 kOe (ratio "
                      f"{(t3.get('E3a') or {}).get('observed_a_TDA_over_a_tri_20kOe')}), the minima "
                      f"count matches B*A/Phi0 at every field (ratios "
                      f"{min(e3b.get('count_ratio_median_by_field', {}).values(), default=None)}-"
                      f"{max(e3b.get('count_ratio_median_by_field', {}).values(), default=None)}), "
                      f"and the H0 death IQR/median is smallest at "
                      f"{e3c.get('argmin_H_kOe')} kOe, reproducing the published re-entrant ordering",
                caveat=f"E3d (psi6) FAILS its pre-stated sub-rules: the value at 3 kOe is "
                       f"{(e3d.get('psi6_global_by_field') or {}).get('3kOe')} against a pre-stated "
                       f"limit of 0.2 and a published 0.035; sub_rules = {e3d.get('sub_rules')}",
                reference=f"{DIR}/report.json")
    src.note_discrepancy(
        "quantum_fluid E3d",
        "the pre-stated psi6 rule has three sub-rules; two pass and 'value_3kOe_below_0.2' fails "
        f"(observed {(e3d.get('psi6_global_by_field') or {}).get('3kOe')}). The post-hoc "
        "stm_psi6_variants.json shows the value depends strongly on the psi6 definition "
        "(three definitions at 3 kOe give "
        f"{ {k: v for k, v in (variants.get('by_field') or {}).get('3kOe', {}).items() if k != 'n_images'} }), "
        "and its own note says 'POST-HOC descriptive; does not change the pre-registered E3d verdict'")

    # ------------------------------------------------- the rejected local file
    src.skip("quantum_fluid domain06 local dataset (domain06_supercon_abrikosov_vortices.npz)",
             f"the source records verdict = {dom06.get('verdict')!r}; report.json "
             "local_file_domain06 explains it was assessed and not used as a measurement. Its alpha "
             "signature (h0 median "
             f"{((dom06.get('alpha_signature') or {}).get('h0') or {}).get('median')}) is recorded "
             "in the source but is a signature of a synthetic lattice with unit spacing, not a "
             "measurement, so no run was created for it")
    for k, v in (rep.get("absent_or_not_used") or {}).items():
        src.skip(f"quantum_fluid: {k}", str(v)[:500])
    src.skip("quantum_fluid persistence diagrams",
             "only top3_h0_bars (three H0 bars) is committed, in calib_pipeline.json and "
             "gpe_tda.json; stm_vortex_tda.json and xy_analysis.json keep no bars at all, only "
             "pooled H0 death statistics and classifier outputs")
    src.skip("quantum_fluid p-values",
             "no p_value, n_null or null-model description exists in any of the seven result JSONs; "
             "the nulls are structural (random_control.per_seed, E1e_shuffle.<T>.shuffled, "
             "f_short_rand) and only their means and a diff_over_se are reported, so every statistic "
             "is stored without a p-value")
    return src.report()
